### ISSUE TITLE
How to model Bezier shapes in Trachel?

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#1]
We have `TSLine`, we can create subclasses of `TSLine`

**Comment by akevalion** [comment]
This is the structure of lines in roassal3
![image](https://user-images.githubusercontent.com/10532890/56007354-6d531a00-5ca6-11e9-8d13-aac6b4ec13ea.png)
Instances of TSBezier have control points, the size of this collection of points must be between 2 and 4

```Smalltalk
v := RSView new.
v addShape: (TSBezier new 
	color: Color red;
	controlPoints: { 0@0. 100@100. 200@0. 300@100 }
	).
box := RSShapeBuilder box draggable size: 100.
e1 := box element.
e1 color: Color blue.
e2 := box element.
v add: e1; add: e2.
l := RSSingleEdgeBuilder bezier
	withVerticallAttachPoint;
	from: e1;
	to: e2; 
	controlPoints: [ :m | [ :a :b| | mid |
		mid := (a + b)/2.
		Array
			with: a
			with: a x @ b y
			with: b x @ a y
			with: b
		 ] ];
	edge.
v add: l.
v open
```

![image](https://user-images.githubusercontent.com/10532890/56008236-8ad5b300-5ca9-11e9-9ef3-5d22b3d7f6a1.png)

**Comment by bergel** [comment]
Looks really good! 
On this example, this bezier may be called `orthoVerticalBezier`, from the class side of `RSSingleEdgeBuilder`

**Comment by akevalion** [comment]
I can not put the name `orthoVerticalBezier` because ortho means another thing `of or involving right angles; at right angles.`
I use `verticalBezier` and `horizontalBezier`
