### ISSUE TITLE
RSControlsView should support keyboard shortcuts

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#10]

**Comment by akevalion** [comment]
RSControlsView now has keyboard shortcuts with TSKeyDown and TSKeyUp

1. letter **I** for Zoom in
2. letter **O** for Zoom out
3. letter **F** for Zoom to fit
4. Key arrows for translate the view
5. shift to speed the translation with key arrows

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/10532890/54855149-03150e00-4cd4-11e9-984f-458c6a6f723a.gif)

**Comment by bergel** [comment]
We need help :-) pressing with '?'

**Comment by bergel** [comment]
'/' to search? Using Spotter?

**Comment by bergel** [comment]
We should use `RSLegendBuilder`
