### ISSUE TITLE
Questions about RSBorder

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#100]
Can you provide some simple examples that use joinRound, capButt, ...?

**Comment by akevalion** [comment]
check these examples example17Borders, example24Polyline

![image](https://user-images.githubusercontent.com/10532890/69378396-0a3e5280-0c8d-11ea-9d16-536af6c9a167.png)

![image](https://user-images.githubusercontent.com/10532890/69378413-11fdf700-0c8d-11ea-8404-a22f92171382.png)
