### ISSUE TITLE
[Roassal3-Matplotlib] Class Names

### ISSUE THREAD

**Issue by olekscode** [ObjectProfile/Roassal3#104]
Needless to say that `PLT` is not a very good class name. I can propose to rename it to `RSPlot`.
As for `PLTPlot` and `PLTScatter`, I would call them `RSLinePlot` and `RSScatterPlot` or `RSLine` and `RSScatter` (if possible).

Because it is a bit confusing to create a plot and add a plot to it.
```Smalltalk
plot := PLT new.
p := PLTPlot new.
plot addPlot: p.
```
But consider this: you create a plot and add a line to it:
```Smalltalk
plot := RSPlot new.
line := RSLine new.
plot add: line.
```
Or draw line on a plot:
```Smalltalk
plot draw: line.
```
This could be a nice API for drawing multiple things on one plot:
```Smalltalk
RSPlot new
    add: (RSScatterPlot new x: age y: salary)
    add: (RSLinePlot new x: age y: age * slope + intercept).
```
It is still a bit confusing to add ScatterPlot and LinePlot to Plot, so maybe we can take some inspiration from [The Grammar of Graphics](https://www.amazon.com/Grammar-Graphics-Statistics-Computing/dp/0387245448) that was implemented as [ggplot](https://ggplot2.tidyverse.org/)

![ggplot-grammar-of-graphics-stack-1](https://user-images.githubusercontent.com/8271691/68719465-68dc4000-05ac-11ea-9aa9-e5aad1b509b7.png)

Here are some examples of how we do things with ggplot:

```R
library(ggplot2)
```
Scatterplot of sepal and petal length of iris flowers with 3 colors denoting classes (species) of flowers: setosa, versicolor, and virginica (the one that I built with Roassal3 and posted on Discord):
```R
ggplot(data = iris, aes(x = Sepal.Length, y = Petal.Length)) +
  geom_point(aes(color = Species))
```
![Scatter](https://user-images.githubusercontent.com/8271691/68719605-ca9caa00-05ac-11ea-8f22-b6f1a446955e.png)

Or the same thing with a regression line and a light theme:

```R
ggplot(data = iris, aes(x = Sepal.Length, y = Petal.Length)) +
  geom_point(aes(color = Species)) + 
  geom_smooth(method='lm', formula= y~x) +
  theme_light()
```
![ScatterRegression](https://user-images.githubusercontent.com/8271691/68719787-5f9fa300-05ad-11ea-8f33-06fde7c17c79.png)

I strongly **do not** recommend making a dependency on DataFrame, but we can take inspiration for the names. For example, `RSLineGeometry` and `RSPointGeometry` (or `RSScatterGeometry`):

```Smalltalk
sepalWidth := (iris column: 'sepal width').
petalWidth := (iris column: 'petal width').

points := RSPointGeometry new
    x: sepalWidth
    y: petalWidth.

regressionLine := RSLineGeometry new
    x: sepalWidth
    y: slope * sepalWidth + intercept.

RSPlot new
    add: points
    add: regressionLine.
```

I'm not sure if this is a good API, but I think that we can learn a lot from The Grammar of Graphics, and it seems like the right thing for Pharo

**Comment by akevalion** [comment]
At this moment the prefeix for all roassal classes is `RS`
