### ISSUE TITLE
[Roassal3-Matplotlib] Types of visualizations

### ISSUE THREAD

**Issue by olekscode** [ObjectProfile/Roassal3#106]
These are the kinds of visualizations that are probably the most important and the most widely used:

- Line plot (+ horizontal and vertical lines)
- Scatterplot
- Boxplot
- Bar chart (+ stacked bar chart)
- Histogram (+ density plot)
- Heat map
- Pie chart

We can also take inspiration from here:

- [Top 50 ggplot2 Visualizations](http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html)
- [The R Graph Gallery](https://www.r-graph-gallery.com/)
- [Matplotlib Gallery](https://matplotlib.org/gallery.html)
- [Seaborn Gallery](https://seaborn.pydata.org/examples/index.html)
- [Plotly Python](https://plot.ly/python/)
- [Plotly R](https://plot.ly/r/)
- [Plotly JavaScript](https://plot.ly/javascript/)

**Comment by akevalion** [comment]
Currently we have almost all that visualization

RSScatterPlot
RSBoxPlot
RSBarPlot+ stacked bar plot
RSHistogram + density plot
RSPie
RSLinePlot

roassal3 does not have Heat map I think we can create it in order to close this issue
