### ISSUE TITLE
We need a TSConstraint

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#11]
We need to do something like: `TSConstraint move: lbl above: ss.`

**Comment by bergel** [comment]
We should import `RTAlignment` from Roassal2, and maybe, define some utility methods, in the same spirit of `TRConstraint`

**Comment by akevalion** [comment]
There is a version of RTAligment and RTResize that works pretty well on Roassal3

**Comment by bergel** [comment]
But we need `RSLocate`...

**Comment by akevalion** [comment]
We have RSLocate

```Smalltalk
	| v shape e1 e2 |
	v := RSView new.
	shape := RSShapeBuilder box
		@ RSDraggable;
		onElement;
		color: TSColorPalette sequential blues3;
		size: 100.
		
	e1 := shape element.
	"e1 @ RSDraggable."
	e2 := shape element.
	e2 size: 20.
	RSLocate new
		padding: 1;
		fix: e1;
		movable: e2;
		inner;
		bottom;
		left;
		stick.
	v addAll: {e1. e2}.
	v @ RSControlsView.
	v open
```

![image](https://user-images.githubusercontent.com/10532890/56069066-4a307500-5d4f-11e9-8105-00a4d6f68137.png)

**Comment by bergel** [comment]
Looks really good! 
Do you think that `RSLocate` can be a subclass of `RSAbstractElementHandling`?

**Comment by akevalion** [comment]
I do not thing so, RSLocate do es not need any method of that class

**Comment by bergel** [comment]
But `RSAbstractElementHandling` has `fixedElement:`, and you have it again in `RSLocate`

**Comment by akevalion** [comment]
```Smalltalk
example10Locate
	<script: 'self new example10Locate'>
	| v shape e1 e2 |
	v := RSView new.
	shape := RSShapeBuilder box
		@ RSDraggable;
		onElement;
		color: TSColorPalette sequential blues3;
		size: 100.
	e1 := shape element.
	"e1 @ RSDraggable."
	e2 := shape element.
	e2 size: 20.
	RSLocate new
		padding: 1;
		inner;
		bottom;
		left;
		stick: e2 on: e1.
	v addAll:{e1. e2}.
	v @ RSControlsView.
	v open
```
I have change the code of RSLocate, fixedElement and movableElement are not instance variables in RSLocate, instead they are arguments in methods `stick:on:` and `move:on`. The main reason to change that is because RSLocate can be use in a lot of elements and not only in a couple. This is useful for RSLabeled, because RSLabeled uses an instance of RSLotate, you can use the same instance for multiple elements

**Comment by akevalion** [comment]
I have added a new animated example of this
![image](https://user-images.githubusercontent.com/10532890/56100834-931d3080-5eeb-11e9-91b8-f545c98c102f.png)
Click on buttons to modify RSLocate.
click on big box to modify the padding of RSLocate

**Comment by bergel** [comment]
Well done!
