### ISSUE TITLE
Zooming in the canvas with keys does not work

### ISSUE THREAD

**Issue by RainerWinkler** [ObjectProfile/Roassal3#114]
Hi,
in the examples it is commented, that scrolling using keys I and O is possible bevore the statement
c @ RSCanvasController.
This does not work for me. I use Windows 10 with a German keyboard. I tested on Pharo 7.0 and Pharo 9.0 64 bit.
BR
Rainer

**Comment by RainerWinkler** [comment]
All the keys from RSHighlightableExamples>>example07HighlightButtons do not work for me.
Moving the buttons with the arrows works, but not always correct. The button may get for instance also smaller when I move then with the button.
M, I,O, Space, ... do not work.
Scrooling with the wheel works.

**Comment by akevalion** [comment]
Hi Rainer I will test it with a windows machine, because I am a mac user, I will update this issue when I fix it

**Comment by Ironirc** [comment]
I examined with logging to Transcript in RSKeyNavigationCanvas>>processKeyUp: evt
Transcript cr; show: evt keyValue.
Releasing my m key returns value 77 (same for capital M and lowercase m)
Instead of using keyValue I presume we can use keyCharacter == $M

**Comment by RainerWinkler** [comment]
Hi @akevalion , 
I made a pull request with a fix according to the analysis of @Ironirc .
Best
Rainer

**Comment by akevalion** [comment]
I have tried in a windows machine with pharo8 and it works
