### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by stacksmith** [ObjectProfile/Roassal3#116]
Is the $22.00 book describing an obsolete version **the only documentation**?

I can't find anything that I can work through even to get a sense of the system.  Even the readme.md file refers to classes not present in my Pharo8 with Roassal3 loaded.  I have no LMModel, RTView, RSView, RSShapeBuilder, etc.

What is the expected learning path for someone with a deep technical understanding of computer science, some Smalltalk and no Roassal?

**Comment by bergel** [comment]
Hi!
I am sorry about this.
We have recently initiated a major documentation effort, available in the wiki page https://github.com/ObjectProfile/Roassal3/wiki

We also have written a number of tutorials.

Let us know how it goes.
