### ISSUE TITLE
OpenStreetMap Support

### ISSUE THREAD

**Issue by olekscode** [ObjectProfile/Roassal3#118]
Roassal2 had a really nice mapping functionality with OpenStreetMaps: http://agilevisualization.com/AgileVisualization/OpenStreetMap/0304-OpenStreetMap.html

But at the moment it is not available in Roassal3

**Comment by akevalion** [comment]
There is a basic example with a new package OpenStreetMap, is not final and has a lot of issues but it is an start

**Comment by olekscode** [comment]
Great! Thank you
I will try it a bit later

**Comment by akevalion** [comment]
done

**Comment by akevalion** [comment]
https://twitter.com/akevalion/status/1686752530846388224
