### ISSUE TITLE
Comment of RSAbstractContainerBuilder is totally useless

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/Roassal3#123]
From Stef
- I still do not know what is a builder.

**Comment by bergel** [comment]
We should write some examples in the wiki page: https://github.com/ObjectProfile/Roassal3/wiki/11-Builder

**Comment by bergel** [comment]
Maybe an example that make the search widget from `example06IterateNext` pluggable to any view?

**Comment by akevalion** [comment]
I have updated the comment of this class
