### ISSUE TITLE
I do not understand how the RSAbstractDecorator can work. 

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/Roassal3#124]
From Stef
- Right now it is just an object point to a builder but there is no delegating API.

**Comment by bergel** [comment]
Again, we need some examples about this class, in the wiki page

**Comment by akevalion** [comment]
I have removed the class RSAbstractDecorator, Roassal now uses 2 types of objects to produces visualizations.

- RSAbstractContainerBuilder, to produce complex visualizations, in a canvas or composite
- RSInteraction.

These classes and subclasses are optional, because users can produce shapes and interactions with other framework
