### ISSUE TITLE
Why RSNormalizer is packaged in RS-Shapes?

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/Roassal3#140]
From Stef

since it looks like no shape use it.

**Comment by akevalion** [comment]
RSNormalizer is more like a utility class to modify some attributes from shapes like size, width, height color, font size, etc.

```Smalltalk
| shapes |
shapes := (1 to: 2) collect: [ :n | RSBox new model: n; yourself ].
	
self assert: shapes size equals: 2.
self assert: shapes first color equals: Color lightGray.
RSNormalizer color
	shapes: shapes;
	normalize: #yourself.
self assert: shapes first color equals: Color green.
```
normalizer changes the attribute based on a metric, normalizer collects that metric from each shape model

**Comment by bergel** [comment]
It was decided to keep normalizer together with shapes as it indeed makes sense
