### ISSUE TITLE
Important issue in RSNiceLabelGenerator

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#143]
For some reason, with the nice label generator seems to locate some values outside the chart. It is not clear why this happens.

Consider the script:
```Smalltalk
x := -5 to: 5 by: 0.1.

g := RSChart new.
d := RSLinePlot new x: x y: (x + 10) log.
g addPlot: d.
g addDecoration: RSVerticalTick new doNotUseNiceLabel.
g
```
It produces:
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/393742/77497061-257fc100-6e2b-11ea-8558-9a071f912cf7.png">

But using the nice labels:
```Smalltalk
x := -5 to: 5 by: 0.1.

g := RSChart new.
d := RSLinePlot new x: x y: (x + 10) log.
g addPlot: d.
g addDecoration: RSVerticalTick new.
g
```

It produces:

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/393742/77497074-2fa1bf80-6e2b-11ea-8d77-8777dc99219e.png">

**Comment by bergel** [comment]
I think this may be linked to the issue found in https://github.com/ObjectProfile/Roassal3/issues/142

**Comment by akevalion** [comment]
This issue is not related to 142 but I will fix it

**Comment by akevalion** [comment]
The error is solve, please check
<img src="https://user-images.githubusercontent.com/10532890/77803905-0d8f8380-705d-11ea-8637-c19e29574fda.png" width="400">

**Comment by bergel** [comment]
The issue is apparently fixed.
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/393742/77811602-31ad8d80-707a-11ea-98f8-7de9e3909e29.png">
