### ISSUE TITLE
Loading the Roassal3 baseline crashes Pharo7

### ISSUE THREAD

**Issue by myroslavarm** [ObjectProfile/Roassal3#144]
I was looking through old issues for Pharo and this one is still relevant: https://github.com/pharo-project/pharo/issues/5231, at least on windows 10

**Comment by akevalion** [comment]
I have loaded Roassal3 version 14 april 2020 on Windows10 on 32 and 64 bits images, without errors

**Comment by akevalion** [comment]
32 bits image pharo7
![image](https://user-images.githubusercontent.com/10532890/79296799-73c43500-7eaa-11ea-9b92-75fd2b3ea532.png)

64 bits image pharo7

![image](https://user-images.githubusercontent.com/10532890/79297874-75432c80-7ead-11ea-9ec0-11bb752ef6f4.png)
