### ISSUE TITLE
Improve the key name extraction 

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#145]
In `trKeyUp:` we can get the name of the key by: `('UP: ', aMorphicEvent key name) traceCr.`

In `trKeyDown:` we can have `('DOWN: ', aMorphicEvent keyCharacter asString) traceCr.`

**Comment by akevalion** [comment]
I have added a new example related to this issue example35KeyEvents
RSKeyEvents now has keyName this allow us to recognize the name of a key
