### ISSUE TITLE
Issue with log scale

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#146]
Log scales are apparently improperly built.

For example
```Smalltalk
x := (-5 to: 500 by: 0.1).
y := x.
chart := RSChart new.
chart addPlot: (RSLinePlot new x: x y: y).
chart addDecoration: (RSVerticalTick new float).
chart yLog.
chart
```
raises an error. 

Other Y scale works well, for example:
<img width="971" alt="image" src="https://user-images.githubusercontent.com/393742/77812268-f9f51480-707e-11ea-8fc0-d77153bac87a.png">

Related work:

- https://matplotlib.org/3.1.1/gallery/pyplots/pyplot_scales.html#sphx-glr-gallery-pyplots-pyplot-scales-py
- Check d3

**Comment by akevalion** [comment]
There is a new scale `NSSymLog ` check example `example09LinearSqrtSymlog`

![image](https://user-images.githubusercontent.com/10532890/80163074-fe8bea80-85a2-11ea-8f18-f77fe123a24d.png)

NSLog only accept domain negatives or positives, but not both, and NSLog does not accept 0 values

NSSymLog is for domains that contains negatives zero and positive values.

**Comment by bergel** [comment]
Here is an updated script:
```Smalltalk
x := (-5 to: 500 by: 0.1).
y := x.
chart := RSChart new.
chart addPlot: (RSLinePlot new x: x y: y).
chart addDecoration: (RSVerticalTick new asFloat).
chart yLog.
chart
```
