### ISSUE TITLE
RSAlignment has some issues

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#15]
```Smalltalk
v := RSView new.
ss := RSShapeBuilder box size: 30; element.
lbl := RSShapeBuilder label elementOn: 'hello'. 

v add: ss.
v add: lbl.

RSAlignment new fixedElement: ss; elements: (TSGroup with: lbl); center.
v open
```
I would expect the label to be at the center of the fixed element, the box. But this is not the case:
![image](https://user-images.githubusercontent.com/393742/54857221-e29d8180-4cdc-11e9-97c1-26b978136fad.png)

**Comment by akevalion** [comment]
I have the sam behaviour in roassal2

```Smalltalk
v := RTView new.
ss := RTBox new size: 30; element.
lbl := RTLabel new elementOn: 'hello'. 

v add: ss.
v add: lbl.

RTAlignment new fixedElement: ss; elements: (RTGroup with: lbl); center.
v open
```

![image](https://user-images.githubusercontent.com/10532890/54968099-3bc51980-4f58-11e9-937f-e83cbbd98956.png)

**Comment by akevalion** [comment]
It is not an issue
