### ISSUE TITLE
Example of Subplots

### ISSUE THREAD

**Issue by rudyn2** [ObjectProfile/Roassal3#159]
It would be nice to add an example of a subplots. For example, if i wanted to have 2 plots in 1 figure. Imagine a matrix of 2x1, i would like to have 1 subplot in the first row, and other one in the second row. Each one with its own labels, titles, etc. It is a really common task and for a beginner would be appreciated. Here an example:

![Example](https://user-images.githubusercontent.com/20200048/78713069-a50b9680-78e7-11ea-95d9-8d0a7aad6c7a.png)

**Comment by bergel** [comment]
https://github.com/ObjectProfile/Roassal3/issues/160

**Comment by akevalion** [comment]
I have created a new example for RSChart example08TwoCharts, I will close this issue because it is duplicated with issue https://github.com/ObjectProfile/Roassal3/issues/160
