### ISSUE TITLE
We need RSAreaPlot

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#166]
Which is similar to:
<img width="394" alt="image" src="https://user-images.githubusercontent.com/393742/79290611-94848e80-7e9a-11ea-95dc-eea0002b1723.png">

**Comment by akevalion** [comment]
I have created a new example example13AreaPlot

![image](https://user-images.githubusercontent.com/10532890/83611069-765c1600-a54e-11ea-982d-6d30c27f0c11.png)

**Comment by akevalion** [comment]
example14AreaPlotWithError

![image](https://user-images.githubusercontent.com/10532890/83713874-49b00900-a5f7-11ea-8404-3aca5e54c533.png)

example15AreaBox

![image](https://user-images.githubusercontent.com/10532890/83713891-52a0da80-a5f7-11ea-9195-883b00383694.png)

example16Series

![image](https://user-images.githubusercontent.com/10532890/83713925-60566000-a5f7-11ea-9ed2-a9c40b8a59ec.png)
