### ISSUE TITLE
Coordinate system should be customizable

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#181]
From @noha 
https://discordapp.com/channels/223421264751099906/300020095844089856/702943959743332472
My main concern which is more a feeling is that there is a pixel-mind in static dimensions in Roassal. So it is more about absolute coordinates in a top-left world. So my example from above. I draw geo coordinates which are bottom-up on our northern hemisphere. So what I need and never achieved in morphic is the way that you cannot define your canvas space. I need a world of -90 to 90 and -180 to 180 geo space that maps properly onto the screen. If a toolkit forces me to calculate everything myself it kill the fun. Morphic kills it with absolute positioning and Roassal has some of these flaws as well. I hope there is a cure for this

**Comment by noha** [comment]
Thank you very much for making this tickets. Just a side note. Whenever I worked with toolkits like Roassal I had the expression that there are three spaces involved. Toolkits often have a device independent space with dimensions 0-1. In my example I have geo coordinates. So I should be able to provide a transformation from WGS84 (<- that is the common geo system) to the internal 0-1-space. The toolkit later renders the 0-1-space onto pixel coordinates.

**Comment by bergel** [comment]
@noha Roassal offers various scale to transform some position. The code given above transform some positions ranging from 0@0
to 1@1 using two scales (one for X and another for Y).
```Smalltalk
vx := 0 to: 1 count: 10.
vy := 0 to: 1 count: 10.

scaleX := NSScale sqrt.
scaleX range: { 100 . -100 }.

scaleY := NSScale sqrt.
scaleY range: { -100 . 100 }.

c := RSCanvas new.

vx do: [ :x |
	vy do: [ :y |
		circle := RSEllipse new size: 10.
		c add: circle.
		circle translateTo: (scaleX scale: x) @ (scaleY scale: y).
	]
].
c
```

**Comment by noha** [comment]
What I want is a global transformation. You see what Roassal should do is to allow a user space (geo coordinates in my case) then you have a transformation of every Point given by the user to the 0@0-1@1 coordinate space Roassal internally operates on. And then on rendering time you transfer the internal space to pixel space. I don't think you can escape this. That is what I see in the design you take the user data and transform it into your internal space. 
What you propse is that the user should everywhere scale its data to fit Roassal. So you expect the user to be there for Roassal and not the other way round. In this case Roassal won't make it. It is the same with my last issue that polygons with geo coordinates cannot be rendered and then I get an answer there are default minScale maxScale numbers (why?) and I have to tweak the scale of the canvas to see my own coordinates. That is why I'm not the only one that finds it is hard to convince Roassal to do something. If you don't want that Roassal stays your expert tool and it is usable by most people you need to understand user needs not try to moderate them away. Sorry for being frank here but I see this attitude for a long time and it is a pitty

**Comment by noha** [comment]
Any news on this? I hope you can see that there a plenty of use cases that do not leave in a coordinate space 0,0 to 100,100. For me doing geo applications roassal is a drag at the moment because it is hard to convince to do the right thing. And I will abandon the use of roassal for this if it won't change

**Comment by bergel** [comment]
Hi @noha ! 
It is an extremely specific feature, which deserves to be carefully considered and not in hurry. We are waiting for Roassal3 to be part of Pharo 9, else, we are exposing ourselves to maintain two different versions of Roassal (the latest one and the one included in Pharo). Again, this is a matter of Human Resources.
Be patient, we will work on it whenever it is possible.

**Comment by akevalion** [comment]
Hello, I will work on this matter.

for now this is a small preview of what is coming, please tell me if this solves your problem, basically I want to change the origin of roassal canvas camera and the position of the shapes(TODO)

```st
canvas := RSCanvas new.
canvas background: 'veryVeryLightGray'.
canvas originCenterMiddle.
canvas originTopLeft.

canvas add: (RSBox new
	position: 200@200;
	extent: 200@200;
	borderColor: 'black';
	model: 'white';
	fill: 255;
	yourself).

canvas add: (RSBox new
	position: 150@150;
	extent: 100@100;
	borderColor: 'black';
	model: 'gray';
	fill: 100;
	yourself).

canvas shapes @ RSPopup.
canvas
```
<img width="546" alt="image" src="https://user-images.githubusercontent.com/10532890/196435895-0e662208-5642-4991-9ba0-68d7b99b735b.png">
If you have an idea of how to handle a new the system coordinates please share it us, then we can work together on that.
