### ISSUE TITLE
Problem in Geometry

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#185]
The following script raises an error:

```Smalltalk
classes := { 'Roassal3-Layouts'. 'Roassal3' }
	flatCollect: [:pkgname | (RPackage organizer
		packageNamed: pkgname) definedClasses ].
shapes := RSGroup new.
classes do: [ :c | shapes add: (RSEllipse new model: c) ].

c := RSCanvas new.
c addAll: shapes.
eb := RSEdgeBuilder orthoVertical.

eb canvas: c.
eb withBorderAttachPoint.
eb connectFrom: #superclass.

RSNormalizer size
	shapes: shapes;
	normalize: [ :c | c numberOfMethods + 5 ].
RSTreeLayout on: shapes.
c @ RSCanvasController @ RSHierarchyPacker
```

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/393742/80440437-cb18cb00-88d6-11ea-9286-7ded311f6ce2.png">
Something is wrong in the Geometry apparently. If I comment the line `eb withBorderAttachPoint.`, then there is no error

**Comment by akevalion** [comment]
Consider

```Smalltalk
classes := { 'Roassal3-Layouts'. 'Roassal3' }
	flatCollect: [:pkgname | (RPackage organizer
		packageNamed: pkgname) definedClasses ].
shapes := RSGroup new.
classes do: [ :c | shapes add: (RSEllipse new model: c) ].

c := RSCanvas new.
c addAll: shapes.
"first set the size"
RSNormalizer size
	shapes: shapes;
	normalize: [ :c | c numberOfMethods + 5 ].

eb := RSEdgeBuilder orthoVertical.
eb canvas: c.
eb withBorderAttachPoint.
eb connectFrom: #superclass.
RSTreeLayout on: shapes.
c @ RSCanvasController @ RSHierarchyPacker
```
![image](https://user-images.githubusercontent.com/10532890/81351121-94d70a80-9091-11ea-8201-f239184afaa3.png)

Geometry can not calculate the intersection between a line and an empty ellipse `size = 0`.
For that reason we need first to set the extent of each ellipse then apply the attach point.

**Comment by bergel** [comment]
Wow... Well spotted!
Well, not sure there is something we should do here.

**Comment by bergel** [comment]
The correct solution is to do a pull request on Geometry that fixes the issue

**Comment by akevalion** [comment]
I have updated roassal3 with this issue.
- I have created a Pr between https://github.com/akevalion/Geometry and https://github.com/pharo-contributions/Geometry
- Roassal3 now depends on https://github.com/akevalion/Geometry until pharo accept the PR

BorderAttachPoint now works for polygons

```Smalltalk

| c shapes |
c := RSCanvas new.
shapes := RSShape withAllSubclasses collect: [ :cls | 
	RSShapeFactory star size: 30; draggable; model: cls; yourself ].
c addAll: shapes.
RSEdgeBuilder arrowedLine 
	withBorderAttachPoint;
	canvas: c;
	connectFrom: #superclass.
RSForceBasedLayout new 
	charge: -500; 
	on: c nodes.
c @ RSCanvasController.
^ c
```

![image](https://user-images.githubusercontent.com/10532890/84230921-0a802d00-aabb-11ea-8ee9-62697d339621.png)
