### ISSUE TITLE
Issue with RSNiceLabel

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/Roassal3#194]
From stef

> defaultNiceLabel
>       | nice |
>       nice := RSNiceLabel new.
>       nice
>               score: 0;
>               min: self minValue;
>               max: self maxValue;
>               step: nice ticks / numberOfTicks.
>       ^ nice
>
> what is score: 0

Milton my point was not that I need to know it.
It was more that the API should let me understand it.
I still do not understand what is the score and a null one for a label
And may be the API should be more like

        nice
                setupForCool;
                min: self minValue;
               max: self maxValue;
               step: nice ticks / numberOfTicks.

**Comment by akevalion** [comment]
I have changed this method

**Comment by bergel** [comment]
This is true. Nice Label is a complex algorithm.

**Comment by bergel** [comment]
We added some comments
