### ISSUE TITLE
Null pattern

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/Roassal3#198]
From Stef

```Smalltalk
mouseStart: evt
        isMoving := true.
        lastStep := nil.
```

You do not use a null pattern for the step?

**Comment by akevalion** [comment]
In this case `RSDraggableCanvas` needs to know the last point when the user moves the canvas with a drag and drop, in order to create an animation. I think for this case we do not need the null pattern

**Comment by bergel** [comment]
We would need to create a class `NullPoint`, which is really odd to have.

**Comment by Ducasse** [comment]
It depends because now are you testing multiple time lastStep ifNotNil: 
if you test is only once this is ok. And a nullPoint could be an absorbing object like does not on translation, rotation .... so this is not strange to me. After it depends on the usage.

**Comment by akevalion** [comment]
In this case last step is used in 3 cases.

```Smalltalk
"when user use mouse click down"
mouseStart: evt
	isMoving := true.
	lastStep := nil.
```

```Smalltalk
"when user moves the mouse with click down"
mouseMove: evt
	| camera p correct |
	isMoving ifFalse: [ ^ self ].
	camera := evt camera.
	lastStep := evt step negated / camera scale.
	correct  := self correctCameraPosition: evt.
	p := (correct - camera position) abs max: 1@1.
	p := p x sqrt @ p y sqrt.
	camera translateBy: lastStep/ p.
	evt signalUpdate.
```

```Smalltalk
"when user perform a mouse click up"
mouseEnd: evt
	| threshold aCanvas camera delta p correct |
	isMoving := false.
	lastStep ifNil: [ ^ self ].
	aCanvas := evt canvas.
	camera := evt camera.
	threshold := 4.
	(lastStep dist: 0@0) < threshold
		ifTrue: [ ^ self checkCamera: aCanvas ].
	"this creates an animation to large to be shown"
	...
```

**Comment by bergel** [comment]
But there are only one check to nil. I close the issue for now, we can always re-open it later on.
