### ISSUE TITLE
The animated force based layout needs improvement

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#203]
Here is an example of now to use the animated force base layout:

```Smalltalk
c := RSCanvas new.
c addAll: ((1 to: 100) collect: [:i | RSEllipse new size: 10; model: i]).

eb := RSEdgeBuilder line.
eb canvas: c.
eb connectFrom: [ :v | v // 2 ].

layout := RSForceBasedLayout new.
layout nodes: c nodes.
layout charge: -30.
layout edges: c edges.
layout start.
c @ (RSForceLayoutStepping new layout: layout)
```

I see no good reason why I need to provide `c edges`, and why I need to call `start`. The code must be made clearer. 

Also, the layout seems to animate for a given number of steps. Which is weird...

**Comment by akevalion** [comment]
Consider the following example.

```Smalltalk
c := RSCanvas new.
c addAll: ((1 to: 100) collect: [:i | RSEllipse new size: 10; model: i]).

eb := RSEdgeBuilder line.
eb canvas: c.
eb connectFrom: [ :v | v // 2 ].
c @ RSForceLayoutStepping.
```

Now the first animation should end when the layout is complete or at least the equivalent of `RSForceBasedLayout on: canvas nodes`.
