### ISSUE TITLE
The suggested loading instruction for "stable" version 0.9 returns error

### ISSUE THREAD

**Issue by GrahamMcLeod** [ObjectProfile/Roassal3#207]
Revspec 'V0.9' not found...

**Comment by bergel** [comment]
Hi @GrahamMcLeod ! Unfortunately, I cannot reproduce your error. Have you tried with a new image? Version 0.9 loads correctly in Pharo 8 and Pharo 9, 64 bits. I cannot run an 32 bits application on my macOS.

Can you provide more detail?

**Comment by bergel** [comment]
We cannot reproduce it. I close it for now, but we can always reopen it later on.
