### ISSUE TITLE
Loaded "latest" after removing previous R3 installation. Example RSChart does not run

### ISSUE THREAD

**Issue by GrahamMcLeod** [ObjectProfile/Roassal3#209]
RSChartExample new example01Markers open

DNU #example01Markers

**Comment by bergel** [comment]
I cannot reproduce this problem. The method `example01Markers` is defined in the class `RSChartExample`.

How did you load Roassal3? You should execute the metacello instruction, as specified in `README.md`.

**Comment by bergel** [comment]
I will close the issue for now. @GrahamMcLeod : Feel free to open it again if the problem persist
