### ISSUE TITLE
Trait names should have Roassal-specific prefix

### ISSUE THREAD

**Issue by pavel-krivanek** [ObjectProfile/Roassal3#211]
Trait names like TContainer and TPositionable are too generic. They need to be renamed to contain Roassal name prefix

**Comment by bergel** [comment]
Maybe as `RSTContainer` or `RSContainerTrait`. I prefer `RSContainerTrait`. At least the name is very clear.

**Comment by akevalion** [comment]
In pharo traits usually starts with T, for that reason we have chagend TSShape or TSBox

**Comment by pavel-krivanek** [comment]
I would vote for RST prefix to let start all Roassal entities on RS (RSTContainer)
