### ISSUE TITLE
Add arrow shape to roassal3

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/Roassal3#22]

**Comment by bergel** [comment]
We need something like `RSEdgeBuilder arrowedLine`, `RSEdgeBuilder arrowedLine offset: 0.7`.
Or `RSEdgeBuilder line startDecoration: (RSArrowLineDecoration)`

**Comment by bergel** [comment]
A nice example is `example16BasicLinePath`

**Comment by akevalion** [comment]
There is a new version of markers for this issue
```Smalltalk
	| c arrow axes circle dataLine |
	c := TSCanvas new.
	arrow := TSPolygon new 
		points: { -10@0. 0@ -10. 10@0 };
		color: Color black;
		size: 10.
	circle := TSEllipse new
		radius: 2.5;
		color: Color red.
	axes := TSPolyline new
		controlPoints: { 10@10. 10@90. 90@90 }.
	dataLine := TSPolyline new 
		controlPoints: { 15@80. 29@50. 43@60. 57@30. 71@40. 85@15 }.
	axes markerEnd: (axes markerStart: arrow).
	dataLine marker: circle.
	c addShape: axes.
	c addShape: dataLine.
	c camera zoomToFit: 250@250.
	c open.
```
At this moment you can add markers in TSPolyline and TSLine, note that marker mid only work on line shapes that has more than 2 control points.
![image](https://user-images.githubusercontent.com/10532890/55849840-0ad01180-5b20-11e9-875c-077f7cdb6e78.png)
