### ISSUE TITLE
Update RSEasel according to Spec2 suggestions

### ISSUE THREAD

**Issue by tinchodias** [ObjectProfile/Roassal3#223]
The superclass suggests using `initializePresenters` and `connectPresenters`. 
There are also some code critics that could be fixed.
I have a PR ready to push.

**Comment by tinchodias** [comment]
Also, accessors to widgets are not required by Spec2 (a difference with Spec1)... so I removed them to only browse the meaninful code.

**Comment by akevalion** [comment]
I can se the branch but I can not see the PR

**Comment by tinchodias** [comment]
Hm, sorry. Now I created #226 .

**Comment by akevalion** [comment]
Is this an issue?

**Comment by tinchodias** [comment]
I didn't know of #54, I created it by separate because I only had this code to submit (already merged in #226 so it's good to be closed).
