### ISSUE TITLE
NSUninterpolateClamp and NSUninterpolateNumber

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#225]
these two classes need some example. Their behavior and usefulness are too hidden.

**Comment by akevalion** [comment]
I think that this issue is for https://github.com/ObjectProfile/NumericScales repository.
This repository does not have examples, only tests, I will create a test/example for this issue

**Comment by akevalion** [comment]
I have added some tests and comments in these classes

**Comment by bergel** [comment]
Thanks!
