### ISSUE TITLE
Being able to resize shapes graphically

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#227]
In Roassal2, we had an interaction that let one resize the size of a shape. Can we have it in Roassal3?

**Comment by bergel** [comment]
This feature should belongs to ObjectStudio I believe

**Comment by akevalion** [comment]
I have added example38Transformable
![image](https://user-images.githubusercontent.com/10532890/82506757-a5927200-9ace-11ea-8d0f-4f6c99612fb1.png)

### Features
- RSTransformable adds a new controls ove the target shapes.
- This interaction only works with shapes without roations and skews. https://developer.mozilla.org/es/docs/Web/SVG/Attribute/transform
- RSTransformable does not work on lines or canvas.
- RSTransformable works on all RSBoundingShapes including RSComposite.

### TODO 

- add a new icon for rotation and add events in order rotate figures
![image](https://user-images.githubusercontent.com/10532890/82507170-93650380-9acf-11ea-908e-05a5670e2d75.png)

- RSTransformable ignores rotations
![image](https://user-images.githubusercontent.com/10532890/82507088-58fb6680-9acf-11ea-8b9e-14d22e9d58a4.png)
![image](https://user-images.githubusercontent.com/10532890/82507112-63b5fb80-9acf-11ea-8ff5-60ba90db8c9f.png)

- maybe add methods to configure the handlers
- maybe set each control size depending on small shapes, for example shapes with size < 1.

**Comment by akevalion** [comment]
Maybe we can close this issue
