### ISSUE TITLE
We should have a treemap

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#234]
Roassal2 has a treemap, it should be ported

**Comment by akevalion** [comment]
Roassal3 has treemaps, but you will need to load the packages from the iceberg repository with the last version of roassal
Roassal3-Treemap
Roassal3-TreemapExamples
![image](https://user-images.githubusercontent.com/10532890/133540749-5f00ee75-04d0-433d-8a0e-292bb41f3117.png)

**Comment by akevalion** [comment]
@bergel can we close this issue?

**Comment by bergel** [comment]
yes
