### ISSUE TITLE
Use Roassal3 as a backend for Telescope

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#236]
Here are the starting points:
  - https://github.com/TelescopeSt/Telescope 
  - https://github.com/TelescopeSt/TelescopeRoassal

**Comment by akevalion** [comment]
Currently roassal3 telescope works well in a lot of examples of telescope

**Comment by bergel** [comment]
https://github.com/TelescopeSt/TelescopeRoassal3
