### ISSUE TITLE
Name of SpMorphicAdapter is not explicit

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#237]
Astares wrote on discord:

> Some more feedback: I think that "SpMorphicAdapter" is a too generic class name, this looks like a generic morphic adopter for Spec - that I can subclass for Spec in general when bridging with morphic.
> But this class is a very Roassal specific class. I wonder why you use the "Sp" Prefix - maybe "RSMorphicAdapter" or "SpRoassalMorphicAdapter" would be a better and more specific name.

**Comment by akevalion** [comment]
@astares SpMorphicAdapter has been renamed to SpRoassalMorphicAdapter

**Comment by astares** [comment]
@akevalion  Thank you!

**Comment by akevalion** [comment]
I think that we can close this issue
