### ISSUE TITLE
Dependency of Geometry

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#241]
Von: Norbert Hartl <norbert@hartl.name>
Betreff: Aw: Geometry package
Datum: 28. Mai 2020 um 14:20:00 MESZ
An: Alexandre Bergel <abergel@dcc.uchile.cl>
Kopie: Stephane Ducasse <stephane.ducasse@inria.fr>, Cyril Ferlicot <cyril.ferlicot@gmail.com>

I've forked the project into pharo-contributions. You can change the repo in your baseline.

Norbert

**Comment by akevalion** [comment]
Roassal3 now depends on 

```Smalltalk
spec package: 'Geometry' with: [ 
	spec repository: 'github://pharo-contributions/Geometry:v1.1.0' ].
```

Should we use the last version of Geometry?

**Comment by bergel** [comment]
> Should we use the last version of Geometry?
We will see this in the future if there is a need
