### ISSUE TITLE
Exporter to PDF

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#246]
Pavel said:

> It would be nice to rewrite this method to do not use the Morphic dependency at all and do not use explicit GC because that is a huge performance killer.

**Comment by tinchodias** [comment]
That's something needed due to the current implementation of the Cairo exporters in Pharo. We can open an issue in Pharo repo and I can fix it (shouldn't be more than 30mins).

**Comment by bergel** [comment]
That would be great :-) Let us know

**Comment by tinchodias** [comment]
Just posted a fix in https://github.com/pharo-project/pharo/pull/7005

**Comment by tinchodias** [comment]
Merged in Pharo 9 today

**Comment by akevalion** [comment]
There is not a reference to  `garbageCollect` in the last version of roassal3exporters
