### ISSUE TITLE
Padding on RSChart

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/Roassal3#248]
RSChart main box should have a padding in order to avoid the content and the box an over drawing

![image](https://user-images.githubusercontent.com/10532890/83706874-97704580-a5e6-11ea-9099-ece588de5959.png)

The correct result with padding should be.

![image](https://user-images.githubusercontent.com/10532890/83706848-86bfcf80-a5e6-11ea-9278-32a5d1eb403f.png)

Will be nice to have this behavior by default

**Comment by akevalion** [comment]
consider:
```Smalltalk

| x y polyfit res y_est y_err c |
x := 0 to: 10.
y := #(3.9 4.4 10.8 10.3 11.2 13.1 14.1 9.9 13.9 15.1 12.5).
polyfit := [ :x1 :y1 :n |  
	"TODO"
	"Need a real polyfit implementation for any n"
	"maybe not in roassal3 maybe in polymath"
	"https://en.wikipedia.org/wiki/Curve_fitting"
	0.9-> 6].
res := polyfit value: x value: y value: 1.
y_est := res key * x + res value.

y_err := x stdev * ( (1/x size) + 
	(( (x - x average) raisedTo: 2) / 
	((x - x average) raisedTo: 2) sum) ) sqrt. 
	

c := RSChart new.
"c padding: 0@ 0."
c addPlot: (RSAreaPlot new x: x y1: y_est + y_err y2: y_est - y_err; color: (Color blue alpha: 0.1) ).
c addPlot: (RSLinePlot new x: x y: y_est; color: Color red).
c addPlot: (RSScatterPlot new x: x y: y).
c addDecoration: (RSHorizontalTick new numberOfTicks: 10; asFloat).
c addDecoration: (RSVerticalTick new numberOfTicks: 3; asFloat).
^ c 
```

This is de default value for RSChart `c padding: 0@ 0.` 
![image](https://user-images.githubusercontent.com/10532890/96757737-389c4480-13ac-11eb-9810-433747aa50fc.png)
`c padding: 20@20`
![image](https://user-images.githubusercontent.com/10532890/96757792-4b167e00-13ac-11eb-9b3c-6f3a5693765d.png)

`c padding: 190@0`

![image](https://user-images.githubusercontent.com/10532890/96757907-79945900-13ac-11eb-9643-1e884134a1c7.png)

This means that with padding you can change the direction of the entire chart, or deform it `c padding: -20 @ -50.`

![image](https://user-images.githubusercontent.com/10532890/96758017-9e88cc00-13ac-11eb-850f-6e955b27a3b5.png)

**Comment by bergel** [comment]
well done!
