### ISSUE TITLE
We need the bimetric lines

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#25]
As we have in Roassal2
![image](https://user-images.githubusercontent.com/393742/55635985-4d988f00-5798-11e9-9c05-3d2c79a29cba.png)

**Comment by akevalion** [comment]
There is a new class TSBimetricLine
<p align="center">
<img src="https://user-images.githubusercontent.com/10532890/56005369-f9ad0f00-5c9d-11e9-8d87-327159b22e3e.png" width="200"/>
</p>
You can use it with

```Smalltalk
	| view e1 e2 box l |
	view := RSView new.
	box := RSShapeBuilder box 
		size: 100;
		draggable.
	e1 := box element.
	e1 color: Color blue.
	e2 := box element.
	e2 translateTo: 400@0.
	l := RSSingleEdgeBuilder bimetricLine
		widthFrom: 50;
		widthTo: 10;
		paint: Color red;
		border: nil;
		withBorderAttachPoint;
		from: e1;
		to: e2;
		edge.
	view addAll: { e1. e2. l}.
	view @ RSControlsView. 
	view open
```
Result
<p align="center">
<img src="https://user-images.githubusercontent.com/10532890/56005487-ad160380-5c9e-11e9-9ce7-09ecf6298a01.png" width="300"/>
</p>

**Comment by bergel** [comment]
Excellent work!
