### ISSUE TITLE
Association en UML

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#250]
From Benoît Verhaeghe: 
> it would be great if the UML engine of Roassal3 support associations, aggregations and so on.
> We would use it to show moose metamodels for example (and why not modifying the metamodels from the vizu O.o )

**Comment by akevalion** [comment]
Consider

```Smalltalk

| builder |
builder := RSUMLClassBuilder new.

builder classes: #(Band Musician Catalog Product Building Room).
builder modelDescriptor
	classname: #yourself;
	instVars: #();
	methods: #();
	superclass: nil;
	aggregations: { #Musician -> #Band. #Product -> #Catalog };
	compositions: { #Room -> #Building }.
	
builder renderer layout flow gapSize: 30.
builder build.
^ builder canvas
```

![image](https://user-images.githubusercontent.com/10532890/94890490-bcba7680-0455-11eb-827d-62d4561db76e.png)

**Comment by bergel** [comment]
looks good!
