### ISSUE TITLE
Issue with barplot horizontal ticks

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/Roassal3#257]
Consider

![image](https://user-images.githubusercontent.com/10532890/84216736-684f4d80-aa98-11ea-9f12-b6536f09ed4d.png)

ticks in roassal chart does not align with the bar plots

![image](https://user-images.githubusercontent.com/10532890/84216787-8917a300-aa98-11ea-89df-ed8ee3584021.png)

**Comment by akevalion** [comment]
Consider: 

```Smalltalk
| experience x c |
experience := { 10. 20. 30. 100 }.
x := 1 to: 4.

c := RSChart new.
c addPlot: (RSBarPlot new x: x y: experience ).
c addDecoration: (RSHorizontalTick new
	fromNames: #(Kael Legion Luna Ember); 
	labelRotation: 0;
	yourself ).
c addDecoration: (RSVerticalTick new integer).
^ c
```

**Comment by bergel** [comment]
Excellent example!
