### ISSUE TITLE
check new libraries for Forcebaselayout

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/Roassal3#258]
Review these links and select the useful code for RSForcebaseLayout

https://github.com/cytoscape/cytoscape.js-euler

https://github.com/cytoscape/cytoscape.js-cola

**Comment by akevalion** [comment]
For https://github.com/cytoscape/cytoscape.js-euler

Euler is similar to RSForceBaseLayout

I used the example https://cytoscape.org/cytoscape.js-euler/
![image](https://user-images.githubusercontent.com/10532890/91925710-96ad8500-eca3-11ea-987f-d73edd0c6d15.png)

And I have created this visualization: 
http://ws.stfx.eu/2VFW7KZGQKXS
![image](https://user-images.githubusercontent.com/10532890/91925753-adec7280-eca3-11ea-8680-e00220b07a8d.png)

Euler uses a lot of methods related to animations. But for roassal3 we already have a package to manage this kind of animations.

**Comment by akevalion** [comment]
For https://github.com/cytoscape/cytoscape.js-cola. This is a connector for a more complex layout https://github.com/tgdwyer/WebCola.

Users of WebCola can use tree.js, cytoscape.js, svg.js or d3js to run 2D or 3D visualizations. This javascript project has:

- 4.5k lines of code
- Constraints object for the layout operation
- Groups of nodes and composite shapes
- Interactions with elements for drag operations

Typically a Constraint looks like: 

```js
{
    "type": "alignment",
    "axis": "x",
    "offsets": [
        {"node": "1","offset": "0"},
        {"node": "2", "offset": "0"},
        {"node": "3", "offset": "0"}
    ]
}
```
Cola API for this example https://github.com/tgdwyer/WebCola/blob/master/WebCola/examples/unix.html

```js
d3cola
                .avoidOverlaps(true)
                .convergenceThreshold(1e-3)
                .flowLayout('x', 150)
                .size([width, height])
                .nodes(nodes)
                .links(edges)
                .jaccardLinkLengths(150);
```

Produces
![image](https://user-images.githubusercontent.com/10532890/91929468-73d39e80-ecac-11ea-9963-e42715176555.png)

**Comment by tinchodias** [comment]
I like from this WebCola example that lines don't overlap over boxes (nodes) as GraphViz. 
Maybe we can try to implement the [A* algorithm](https://en.wikipedia.org/wiki/A*_search_algorithm) to have it in RS3.
Sorry if this comment is off-topic.

**Comment by bergel** [comment]
I am not sure how A* algorithm helps doing a layout. It seems to be an algorithm to search for path no?

**Comment by tinchodias** [comment]
You are right, I'm not sure if it fits the requirement. I had that idea because maybe after the force layout algorithm finds places for the nodes, then a pass of this algorithm on each edge could the polygon or bezier to avoid overlapping the nodes.

**Comment by bergel** [comment]
Interesting idea!

**Comment by akevalion** [comment]
I think we can close this issue
