### ISSUE TITLE
Histogram needed

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#262]
We need one

**Comment by akevalion** [comment]
Roassal3 has RSHistogram

**Comment by akevalion** [comment]
```Smalltalk
RSHistogramExample new example04BinningStrat
```
![image](https://user-images.githubusercontent.com/10532890/133540571-dc72eb1a-f377-4ff6-b136-c2c21131003d.png)

**Comment by akevalion** [comment]
@bergel can we close this issue?

**Comment by bergel** [comment]
yes
