### ISSUE TITLE
Bug in RSHorizontalTick>>fromNames:

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#264]
Consider

```Smalltalk
x := 1 to: 3.
data := x sqrt.
c := RSChart new.
d := RSLinePlot new y: data.
c addPlot: d.
"c addDecoration: (RSHorizontalTick new fromNames: #('a' 'b' 'c'))."
c addDecoration: (RSHorizontalTick new fromNames: x).
c
```

The script gives the correct output:
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/393742/85090612-89f4b700-b1b3-11ea-93c6-06fbcb30b8a9.png">

But this version:

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/393742/85090671-b3adde00-b1b3-11ea-9573-8a1c7ee09b4e.png">

The horizontal ticks begins with `a` `a`, which is wrong

**Comment by akevalion** [comment]
I have fixed this issue

**Comment by bergel** [comment]
works well
