### ISSUE TITLE
Redrwaing chart gets weird effect

### ISSUE THREAD

**Issue by melkyades** [ObjectProfile/Roassal3#266]
Test system: Ubuntu20.04, Pharo8, roassal 0.9.1 and latest.

---

When you create a chart and inspect it, you get a Canvas tab showing the result. Now, if you switch to raw view
and select _self_, you get a split view. After that, you can select canvas tab on the right side, which is useful for modifying it on-the-fly:

![image](https://user-images.githubusercontent.com/315241/85634895-fd367700-b652-11ea-8d26-edc90dafc9c6.png)

now, if on the left you select other variable and then self again, the chart starts getting weird. The same if you click
on the refresh button on the top right corner of the inspector.

![image](https://user-images.githubusercontent.com/315241/85634766-97e28600-b652-11ea-9633-31c2451a8f41.png)

The charting code is this:

```
x := -3.14 to: 3.14 count: 100.
y := x sin.

c := RSChart new.
p := RSLinePlot new x: x y: y.
c addPlot: p.

c title: 'Sine function'.

c addDecoration: (RSXLabelDecoration new title: 'X axis'; offset: 15).
c addDecoration: (RSYLabelDecoration new title: 'Y axis'; offset: -35).

c addDecoration: (RSHorizontalTick new fontSize: 10).
c addDecoration: (RSVerticalTick new fontSize: 10).
c maxValueY: 1.1; minValueY: -1.1
```

**Comment by bergel** [comment]
Thanks @melkyades ! 
I was able to reproduce the scenario you describe. But it seems that there is no easy solution to fix this. 
A clear way to fix this would be to remove the automatic call to `build`. 

One version of your script that does not present the problem could be:

```Smalltalk
x := -3.14 to: 3.14 count: 100.
y := x sin.

c := RSChart new.
p := RSLinePlot new x: x y: y.
c addPlot: p.

c title: 'Sine function'.

c addDecoration: (RSXLabelDecoration new title: 'X axis'; offset: 15).
c addDecoration: (RSYLabelDecoration new title: 'Y axis'; offset: -35).

c addDecoration: (RSHorizontalTick new fontSize: 10).
c addDecoration: (RSVerticalTick new fontSize: 10).
c maxValueY: 1.1; minValueY: -1.1
c build.
c canvas
```

Having to manually call `build` can be easily enforced by removing the call to `build` in:
```Smalltalk
RSChart>>gtInspectorViewIn: composite
	<gtInspectorPresentationOrder: -10>
	composite roassal3
		title: ['Canvas'];
		initializeCanvas: [ self build; canvas ] "remove build"
```

But one, would then need to _always_ use `build` when building a chart in a playground... There is no clear and obvious solution here...

**Comment by akevalion** [comment]
I have fixed this now builders reset its content when update.
