### ISSUE TITLE
Text width are wrong in Pharo 8

### ISSUE THREAD

**Issue by tinchodias** [ObjectProfile/Roassal3#271]
They work well in Pharo 9, but may be nice to have them in current stable release.

Is this a decision? I know that, alternatively, P8 users could install some old release of Roassal3 when this was working well.

**Comment by akevalion** [comment]
There are metrics provider for Roassal3, I think we can close this issue

![image](https://user-images.githubusercontent.com/10532890/93793662-7cfdbe80-fc0d-11ea-901b-dbcd9656ff41.png)
