### ISSUE TITLE
Bug when combining bar and line plots

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#272]
Consider:
```Smalltalk
x := -3.14 to: 3.14 count: 10.

c := RSChart new.
c addPlot: (RSBarPlot new x: x y: x cos).
c addPlot: (RSLinePlot new x: x y: x sin).

c title: 'Sine and Cosine functions'.
c xlabel: 'X axis'.
c ylabel: 'Y axis'.

c 
```
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/393742/88721542-e50cb880-d126-11ea-8453-1d686f32d1a7.png">

If you invert the way plots are added, you have something more meaningful:
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/393742/88721757-053c7780-d127-11ea-8c5e-a81eeb18c149.png">

**Comment by akevalion** [comment]
I have fixed this issue 
![image](https://user-images.githubusercontent.com/10532890/94228201-c9c5eb80-fed2-11ea-99f4-28cbb73f6371.png)
