### ISSUE TITLE
Font measurements oddities

### ISSUE THREAD

**Issue by pavel-krivanek** [ObjectProfile/Roassal3#274]
Let's take this example that tries to draw a box of the same extent as the label has

```smalltalk
canvas := RSCanvas new.

text := 'Some text'.
fontSize := 13.333333333333334.
fontSize := 13.

font := LogicalFont familyName:  'Source Sans Pro' pointSize: fontSize.

rawExt := CairoFontMetricsProvider new
		font: font;
		extentsOf: text.
ext := RSTextExtents new
		from: rawExt;
		yourself.
		
label := RSLabel new
	font: font;
	text: text;
	yourself.
	
label fontSize: fontSize.

box := RSBox new 
	extent: ext width @ ext height;
	color: Color green;
	yourself.
		
canvas addShape: box.
canvas addShape: label.
```

In this form, it will work correctly. But:
- if you use the `fontSize` as  13.333333333333334, it will not match. It is relevant because the default font has this setting (`RSLabel new font pointSize`).
- if you remove the line `label fontSize: fontSize.`, it will not match. It is quite strange to need to explicitly define the font size if you do not change it
- if you use a more complicated string like `'Příliš žluťoučký kůň úpěl ďábelské ódy'`, it will not match

**Comment by akevalion** [comment]
With this script 

```Smalltalk
canvas := RSCanvas new.

text := 'Some text'.
fontSize := 13.333333333333334.
"fontSize := 13."

font := LogicalFont familyName:  'Source Sans Pro' pointSize: fontSize.
		
label := RSLabel new
	font: font;
	text: text;
	yourself.
	
label fontSize: fontSize.

box := RSBox new 
	extent: label width @ label height;
	color: Color green;
	yourself.

canvas addShape: box.
canvas addShape: label.
canvas zoomToFit.
```

![image](https://user-images.githubusercontent.com/10532890/92215271-85f73d80-ee62-11ea-8062-13629269689d.png)

And with the word `'Příliš žluťoučký kůň úpěl ďábelské ódy'`

![image](https://user-images.githubusercontent.com/10532890/92215689-29485280-ee63-11ea-90d3-48fde96326a2.png)

But Also there are some issues where this can not work well.

Like this example
```Smalltalk
c := RSCanvas new.
words := String loremIpsum splitOn: ' '.

"words ," #(
PŘÍLIŠ ŽLUŤOUČKÝ KŮN ÚPĚL ĎÁBELSKÉ ÓDY
ca caff Šca Šcaff Žca Žcaff Sca Scaff Zca Zcaff w . Ů) do: [ :word | 
	c add: (RSLabel new
		"fontName: 'Viner Hand ITC';"
		text: word;
		yourself)].
RSFlowLayout on: c nodes.
c showEncompassingRectangles.
can := RSCanvasController new.
can configuration
	maxScale: 40.
c @ can.
c

```
![image](https://user-images.githubusercontent.com/10532890/92215762-43823080-ee63-11ea-8077-c760cc122929.png)

![image](https://user-images.githubusercontent.com/10532890/92215893-7a584680-ee63-11ea-9a99-96b234b3b259.png)

Could please you try the last version of roassal3 with your project and tell us how it goes?

**Comment by bergel** [comment]
There are now several ways to compute the extends of labels:

<img width="746" alt="image" src="https://user-images.githubusercontent.com/393742/93939869-cd6b3e00-fd2b-11ea-943a-ed3970ecb45f.png">

These metric providers can be used using: 
```Smalltalk
mp := RSCairoMetricsProvider new.

c := RSCanvas new.
words := String loremIpsum splitOn: ' '.

"words ," #(
PŘÍLIŠ ŽLUŤOUČKÝ KŮN ÚPĚL ĎÁBELSKÉ ÓDY
ca caff Šca Šcaff Žca Žcaff Sca Scaff Zca Zcaff w . Ů) do: [ :word | 
	c add: (RSLabel new
		metricsProvider: mp;
		text: word;
		yourself)].
RSFlowLayout on: c nodes.
c showEncompassingRectangles.
can := RSCanvasController new.
can configuration
	maxScale: 40.
c @ can.
c
```

Which produces:
<img width="752" alt="image" src="https://user-images.githubusercontent.com/393742/93939921-e673ef00-fd2b-11ea-86e9-f97eb94172e6.png">

**Comment by bergel** [comment]
@pavel-krivanek Can we close this issue?
