### ISSUE TITLE
UML tabs

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#276]
Feedback on the UML tabs.

I think that trying to always get the same font size would be good. 
Also when the fonts are small (large zoom out) the fly by help could be the full class instead of just the name.

**Comment by akevalion** [comment]
I have changed UML for roassal3

In this suggestion

![image](https://user-images.githubusercontent.com/10532890/91934433-61139680-ecb9-11ea-9450-5368ac3d3b9e.png)

**Comment by akevalion** [comment]
I think that we can close this issue
