### ISSUE TITLE
linear scale of colors

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#277]
It seems that one cannot have more than two colors in a linear scale. Can this be fixed?

For example
```Smalltalk
sc := NSScale linear range: { Color blue . Color white . Color red }.

c := RSCanvas new.
0 to: 1 by: 0.1 do: [ :i |
	s := RSBox new size: 10; model: i; color: (sc scale: i).
	c add: s ].

RSHorizontalLineLayout on: c shapes.
c
```
It produces:
<img width="728" alt="image" src="https://user-images.githubusercontent.com/393742/90987635-c31f1e00-e58c-11ea-8750-85080196f304.png">

I would expect the colors to go from blue, white, and red

**Comment by akevalion** [comment]
You need to use a similar domain size of your range size

```Smalltalk
sc := NSScale linear 
	domain: #(0 0.5 1);
	range: #(blue white red).

c := RSCanvas new.
0 to: 1 by: 0.1 do: [ :i |
	s := RSBox new size: 10; model: i; color: (sc scale: i).
	c add: s ].

RSHorizontalLineLayout on: c shapes.
c
```

![image](https://user-images.githubusercontent.com/10532890/91107269-db517480-e642-11ea-8377-2244dabace7f.png)

**Comment by bergel** [comment]
Okay, but this is a bit cumbersome...
