### ISSUE TITLE
Selecting a shape

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#280]
When I select a shape that has a model, the shape is highlighted with a blue border and an inspector appears. For example, consider the example:

```Smalltalk
c := RSCanvas new.
1 to: 10 do: [ :i |
	c add: (RSBox new size: 10; model: i) ].

RSGridLayout on: c shapes.
c @ RSCanvasController
```
The inspector shows me the following:
<img width="896" alt="image" src="https://user-images.githubusercontent.com/393742/91646231-59e85080-ea4d-11ea-827a-2db96df7cb5e.png">
I have selected the second box, and it is highlighted with a blue border. 

However, If I have more boxes, the blue border is not visible anymore. For example, replacing `10` by `100` produces:
<img width="902" alt="image" src="https://user-images.githubusercontent.com/393742/91646251-88662b80-ea4d-11ea-8a8e-fbe36401c352.png">

The reason is because the border width depends on the zooming level, which should not

**Comment by akevalion** [comment]
updated the interaction `RSSelectionPresentation`. Now this interaction adds a shadow with border not depending on RSCamera. you can change the padding and the shadow color. and also the shadow follows the box when dragging.

 Consider the following example
```Smalltalk
| c context int |
c := RSCanvas new.
1 to: 100 do: [ :i |
	c add: (RSBox new size: 10; model: i) ].
c shapes @ RSDraggable.
RSGridLayout on: c shapes.
c @ RSCanvasController.

"This is the default context for the inspector"
context := RSInteractiveContext new.
int := context interactionsToBeRegistered detect: [ :i | i class = RSSelectionPresentation ].
int 
	padding: 5;
	shadowColor: (Color red alpha: 0.1).
c inspectorContext: context.

^ c
```

![image](https://user-images.githubusercontent.com/10532890/91709071-36f29500-eb50-11ea-9501-81d13be6c2f9.png)

**Comment by bergel** [comment]
Super!
