### ISSUE TITLE
Issue with RSCanvasController

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#281]
When I inspect the following code:
```Smalltalk
c := RSCanvas new.

shapes := (1 to: 100) collect: [ :v |
	RSBox new model: v.
].

c addAll: shapes.
RSNormalizer size 
	shapes: shapes;
	from: 10;
	to: 30;
	normalize: #yourself.
RSGridLayout on: shapes.
c @ RSCanvasController
```

I get:

<img width="803" alt="image" src="https://user-images.githubusercontent.com/393742/92470371-9434b900-f1d6-11ea-87df-96d38a2cfd72.png">

I have to press space to have all the shapes in the window...
Why is it not per default, as before?

**Comment by akevalion** [comment]
I think that we can close this issue

**Comment by bergel** [comment]
work well!
