### ISSUE TITLE
How to set the height of labels?

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#282]
How can I set the font size of the label?
```Smalltalk
c := RSCanvas new.

shapes := (1 to: 100) collect: [ :v |
	RSBox new model: v.
] as: RSGroup .

c addAll: shapes.
RSNormalizer size 
	shapes: shapes;
	from: 10;
	to: 30;
	normalize: #yourself.
RSGridLayout on: shapes.

ll := RSLabeled new.
ll shapeBuilder labelShape height: 30.
shapes @ ll.

c @ RSCanvasController
```

It produces:

<img width="806" alt="image" src="https://user-images.githubusercontent.com/393742/92470574-ed045180-f1d6-11ea-8890-ed522c2c62a9.png">

All the numbers should have the same height than the biggest box.

**Comment by akevalion** [comment]
Try to use method `fontSize:`.

**Comment by bergel** [comment]
I have just added the method `RSLabeled>>fontSize:`
Thanks @akevalion
