### ISSUE TITLE
Letting each class render itself

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#284]
@ducasse wrote:
> can you have a look at what I did for Microdown. 
>	buildMicroDownUsing: aBuilder withComment: aString
>The comment renderer asking the class to know how to template it. 
>Guess what? double dispatch. 
>
>This way we can decide what we want to show for each kind of classes.
>This is why a baseline displays something different than a TestCase than a Class.
>
>Could you introduce two hooks so that the class can decide 
>	- if it wants to get a UML display. I do not see the need for a baseline to be display in UML as a package or a class
>	This way we can avoid to have an extra pane for nothing. (now I’m not sure that calypso let it do it simply).
>	- a hook to call roassal so that the class can decide potentially what to show.
>
>This way we can get a kind of visitor.

**Comment by bergel** [comment]
Need to check `buildUMLCanvasWithBrowserTool: tool`

**Comment by akevalion** [comment]
Currently uml builder uses a method in each class
```
buildUMLCanvasWithBrowserTool: tool
	^ nil
```
any class can override this method and return a roassal canvas class, this canvas will be displayed in UML-Calypso tab
