### ISSUE TITLE
Error with the Roassal World Menu.

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#285]
Click on Tools, Roassal3, Examples and get an error

**Comment by akevalion** [comment]
RSWorldMenu now has a method called `browseExample`. This loads examples of this release:
github://ObjectProfile/Roassal3:v0.9.4

**Comment by bergel** [comment]
Instead, we should use the Baseline already loaded...

**Comment by bergel** [comment]
Fixed
