### ISSUE TITLE
What loadShape: is about?

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#291]
A method comment with an example would be great

<img width="574" alt="image" src="https://user-images.githubusercontent.com/393742/93023254-0994f500-f5ee-11ea-8cc3-a10537383a48.png">

**Comment by akevalion** [comment]
This is an example method before cornerRadious on Roassal3 for RSBox then I think I chan update this example and remove this utility method

**Comment by akevalion** [comment]
I have removed this method and methods related to this method

**Comment by bergel** [comment]
Not there anymore
