### ISSUE TITLE
Zooming in RSChart

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#295]
Would be great to be able to select a portion of a graph to zoom in. As a reference point, we had this feature in Roassal2 and Matplotlib does it.

**Comment by akevalion** [comment]
We have RSZoomTickDecoration

<img width="999" alt="image" src="https://github.com/ObjectProfile/Roassal3/assets/10532890/a712cea0-7c99-4c38-9dc8-bd5c4779ab0f">

<img width="1000" alt="image" src="https://github.com/ObjectProfile/Roassal3/assets/10532890/7bcf464b-9fa5-4ef5-bcc1-067d17d60076">
