### ISSUE TITLE
 UML diagram should not be displayed when clicking on a package if the user already looked a comment.

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/Roassal3#297]
The flow should be: 
	ALWAYS respect previous selection.
	When I’m browsing a comment the next click should browse a comment. 
	When I’m browsing a class definition the next click should browse a class definition
	When I’m browsing a uml view, the next click should browse an uml view.
 
Else this is SUPER annoying.

**Comment by bergel** [comment]
a way to reproduce this issue:
---
If you select a class then you get an UML diagram while you would like to see the class comment.

Select a class you see the comment
Select a package (you see the comment)
relect the package of the previous class and you get the UML
and from then on you are screwed.

You are trapped in the UML view forever. 
---

**Comment by bergel** [comment]
Work well!
