### ISSUE TITLE
UML in Calypso

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#30]
We need a UML tab here:
![image](https://user-images.githubusercontent.com/393742/56328898-0c688d80-614f-11e9-9ee8-ce7631b7bea1.png)

**Comment by akevalion** [comment]
For Iceberg we have this, we need to review this and work in details

![image](https://user-images.githubusercontent.com/10532890/56557561-8e025600-6569-11e9-8259-ffeb7479e809.png)

**Comment by bergel** [comment]
Well done!
