### ISSUE TITLE
Check DIG-COLA

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#300]
The creator of Cola wrote me:
> My co-author Yehuda Koren who was working with the graphviz team at AT&T at the time, implemented the technique described in this ["DIG-COLA" paper](https://www.researchgate.net/publication/221005984_DIG-COLA_Directed_Graph_Layout_through_Constrained_Energy_Minimization) in graphviz.  It's still there under a command line option.  More of our constraint-based layout techniques are available in C++ in the libraries at [adaptagrams.org](adaptagrams.org) and in [cola.js](cola.js).  The big advantage of these over graphviz is that they allow interaction with the layout.

**Comment by akevalion** [comment]
I have created a request in order to read the paper
