### ISSUE TITLE
Dependencies between pharo baselines

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#305]
what would be cool is to see how we can display the dependencies between Pharo baseline

**Comment by bergel** [comment]
Kind of related to Issue #284

**Comment by akevalion** [comment]
Currently there is a new tool broswer in Roassal3-Experimental package.
 To explore dependencies of baselines
![image](https://user-images.githubusercontent.com/10532890/97745623-e7850280-1ac7-11eb-92dc-5fdcca237edb.png)

**Comment by bergel** [comment]
well done!
