### ISSUE TITLE
'offset' the marker of a line doesn't work anymore

### ISSUE THREAD

**Issue by CelineDknp** [ObjectProfile/Roassal3#306]
With the newest commit fixing the hover issue on Arrowed/PolyLine with a custom marker, the offset property seems to have stop to work. This used to work:
`RSMarker new shape: aShape; 
			 offset: anInteger`
Now, the shape isn't offset anymore (even if the property 'offset' has the correct value).

**Comment by akevalion** [comment]
@CelineDknp I will review this

**Comment by akevalion** [comment]
I have fixed this! `example08Markers` produces an animated version of
![image](https://user-images.githubusercontent.com/10532890/96913005-787d2d80-1479-11eb-98a4-7a0c7ee8bb8b.png)

**Comment by CelineDknp** [comment]
Perfect, thx 8 I confirm it's fixed for me as well

**Comment by bergel** [comment]
Well done! Thanks!
