### ISSUE TITLE
Line draw order

### ISSUE THREAD

**Issue by ronsaldo** [ObjectProfile/Roassal3#307]
Some lines in the UML diagram seem to be drawn in the wrong order. The issue is quite small and seems to be noticeable on large zoom levels (See the attached picture):

![draw-order-issue](https://user-images.githubusercontent.com/1550655/97293869-89e58180-184d-11eb-8742-6f8bd1cd73ad.png)

**Comment by akevalion** [comment]
I have updated this with an offset related to the border width
![image](https://user-images.githubusercontent.com/10532890/98295814-cc673680-1f90-11eb-8214-f83336136e19.png)

Let me know If this is was you expected

**Comment by bergel** [comment]
Well done! @ronsaldo , What do you think about it?
