### ISSUE TITLE
Why RSCanvas has a nodes and edges variables?

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#319]
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/393742/100810817-07397e80-3418-11eb-9064-02550bec6067.png">
This makes no sense apparently...
This should be cleaned up

**Comment by akevalion** [comment]
RSCanvas is a combination of previous classes from Roassal2, RTView and TRCanvas.
TRCanvas has shapes, and fixed shapes
RTView has elements(nodes) and edges, shortcuts to access node shapes or line shapes.

**Comment by akevalion** [comment]
I will close this issue, but remember
Canvas 
- shapes: all shapes affected by the camera, by default all shape visualizations are in this group.
- fixedShapes: all shapes unaffected by the camera.
- nodes: all bounding shapes `RSBoundingShape`, it may contain shapes affected by the camera or not.
- lines: all line shapes `RSAbstractLine`,  it may contain shapes affected by the camera or not
