### ISSUE TITLE
RSCairoCachedMetricsProvider does not like empty labels

### ISSUE THREAD

**Issue by pavel-krivanek** [ObjectProfile/Roassal3#320]
If a `RSCairoCachedMetricsProvider` wants to measure extent (`extentOf:`) of a label containing empty string, it fails because `sum` message cannot work on an empty collection.

see `RSCairoCachedMetricsProvider>>#extentsOf:`

**Comment by akevalion** [comment]
I have fixed this in last commit

**Comment by bergel** [comment]
Fixed
