### ISSUE TITLE
Shadowed variable names in RSCanvas, RSShape, RSComposite

### ISSUE THREAD

**Issue by astares** [ObjectProfile/Roassal3#321]
In the CI output log for PRs on Pharo 9 issues  I see the following warnings on Roassal classes:

SystemNotification: RSCanvas>>numberOfEdges(edges is shadowed)
SystemNotification: RSCanvas>>numberOfEdges(edges is shadowed)
SystemNotification: RSCanvas>>numberOfNodes(nodes is shadowed)
SystemNotification: RSCanvas>>numberOfNodes(nodes is shadowed)
SystemNotification: RSComposite>>numberOfEdges(edges is shadowed)
SystemNotification: RSComposite>>numberOfEdges(edges is shadowed)
SystemNotification: RSComposite>>numberOfNodes(nodes is shadowed)
SystemNotification: RSComposite>>numberOfNodes(nodes is shadowed)
SystemNotification: RSShape>>printOn:(model is shadowed)
SystemNotification: RSShape>>printOn:(model is shadowed)

which means we have temporary local variables (or block variables) with the same name as an existing ivar

These cases should be cleaned in Rossal3 for the Pharo 9 image

**Comment by akevalion** [comment]
I have cleaning these issues. This change will be present in the next release.

**Comment by astares** [comment]
@akevalion Thanks!

Ideally we can provide a lint rule in base image so that a message is displayed to warn.
For this I opened https://github.com/pharo-project/pharo/issues/8009 on pharo-project

**Comment by bergel** [comment]
Cleaned in v0.9.6c
