### ISSUE TITLE
RSUMLClassBuilder: interfaces, associations, dependencies

### ISSUE THREAD

**Issue by fuhrmanator** [ObjectProfile/Roassal3#322]
I had a look at Roassal3 examples for UML and it's nice to see aggregation and composition in `RSUMLClassBuilder`. 

Are there plans to support interfaces, associations and dependencies from the builder?

**Comment by akevalion** [comment]
Try this example `example10AggregationComposition`

![image](https://user-images.githubusercontent.com/10532890/118023315-69819e00-b32b-11eb-9a51-ef82d97b7c3c.png)

you can create direct lines with associations, is not perfect but is works for simple examples

**Comment by bergel** [comment]
good!
