### ISSUE TITLE
RSUMLPackageCalypso does not respect RSUMLCalypsoSettings>>useCalypsoUML

### ISSUE THREAD

**Issue by gcorriga** [ObjectProfile/Roassal3#332]
Copied from https://github.com/pharo-project/pharo/issues/8313

Describe the bug
The System Browser shows the UML-Package tab for a given package even if Calypso UML has been disabled in the settings.

To Reproduce

Go to Pharo->Settings, then select Code Browsing->Calypso Browser
Make sure the Calypso UML checkbox is unticked.
Go to Tools->System Browser and select any package
The UML-Package tab will be shown.
Expected behavior
The UML-Package tab should not appear

Version information:
Windows 10, with the latest headless vm
Build information: Pharo-9.0.0+build.1026.sha.93d6505fa6afca97eabb854e832cca5f3b5255b3 (64 Bit)

**Comment by gcorriga** [comment]
RSUMLPackageCalypso class>>#shouldBeActivatedInContext: needs to be modified as follows:

shouldBeActivatedInContext: aBrowserContext
^RSUMLCalypsoSettings useCalypsoUML
and: [aBrowserContext isPackageSelected and: [aBrowserContext isClassSelected not]]

**Comment by akevalion** [comment]
Fixed!
Thank you very much for the feedback

**Comment by bergel** [comment]
The bug is fixed in the last version of Roassal3. We will soon merge it into the standard Roassal3
