### ISSUE TITLE
new kind of bezier lines

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#333]
Having something like:

<img width="636" alt="image" src="https://user-images.githubusercontent.com/393742/104057340-bf550680-51d0-11eb-86d3-3809ba1e0f1a.png">

Could be named `directedBezier`

We could also have `arrowedDirectedBezier`

**Comment by akevalion** [comment]
Check `example42DirectedBezier`
![image](https://user-images.githubusercontent.com/10532890/104762862-d2715480-5743-11eb-9c82-a956be9065f1.png)

**Comment by bergel** [comment]
Well done!
