### ISSUE TITLE
Histogram for roassal3 

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/Roassal3#336]
Roassal3 does not have a simple way to construct a histogram chart
based on this article, histogram is not a bar plot

https://www.forbes.com/sites/naomirobbins/2012/01/04/a-histogram-is-not-a-bar-chart/?sh=25356066d775

**Comment by akevalion** [comment]
@SergeStinckwich There is a new plot  RSHistogramPlot and additionally new method `rsHistogram`, check `RSHistogramExample` to test it.

![Uploading image.png…]()

**Comment by bergel** [comment]
Something I am not sure. Consider the following script:
```Smalltalk
values := #(0.5 0.5 0.3 -0.2 1.6 0 0.1 0.1 0.6 0.4).

c := RSChart new.
plot := RSHistogramPlot new x: values.
c addPlot: plot.
c addDecoration: RSVerticalTick new.
c addDecoration: RSHorizontalTick new.
^ c
```

It gives: 
<img width="932" alt="image" src="https://user-images.githubusercontent.com/393742/111134571-07e7c200-857c-11eb-91a8-e379d193bb49.png">

But according to where I got the data: https://www.mathsisfun.com/data/histograms.html 
I should obtain:
<img width="704" alt="image" src="https://user-images.githubusercontent.com/393742/111134813-441b2280-857c-11eb-9c5a-2b579d160d6f.png">

I tried the three different binning strategy and the result is all the same.

**Comment by akevalion** [comment]
Try this

```Smalltalk
values := #(0.5 0.5 0.3 -0.2 1.6 0 0.1 0.1 0.6 0.4).
c := RSChart new.
plot := RSHistogramPlot new x: values; bins: #(-0.5 0 0.5 1 0.5 1 1.5 2).
c addPlot: plot.
c addDecoration: RSVerticalTick new.
c addDecoration: RSHorizontalTick new doNotUseNiceLabel.
^ c
```

- Bins, can be a number or array of sorted numbers
- By default bins  size  is 10
- For the previous example bins are ` #(-0.5 0 0.5 1 0.5 1 1.5 2).`
- First bin is `#(-0.5 0) ` second bin is `#(0 0.5)`
- All bins but last use this expression to calculate the number of values in each bin `start   <= n and: [n  < end]`
- Last bin uses this expression `n between: start and: end`

**Comment by akevalion** [comment]
I think we can close this issue

**Comment by bergel** [comment]
good
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/393742/118326738-ac976900-b505-11eb-94d3-4c698e093a52.png">
