### ISSUE TITLE
Issue with Graphviz

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#341]
Drag and drop of a node does not work well. Consider the following example with `example08RoassalPackages`

![image](https://user-images.githubusercontent.com/393742/110646587-516c9180-81b7-11eb-99cd-5d3b538e09ac.png)

**Comment by akevalion** [comment]
Should be fixed now

![image](https://user-images.githubusercontent.com/10532890/111387030-de1dc080-868b-11eb-90a3-456160d5b64a.png)
