### ISSUE TITLE
Do we really need RSCustomCPController?

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#342]
Since we have `RSBlockCPController`, the class `RSCustomCPController` seems not useful.

**Comment by akevalion** [comment]
RSCustomCPController is more like an example for users to understand how to create a new Control points controller, for lines.
RSBlockCPController is also kind of example. because you can use it to craft new visualizations, but the correct way should be create a subclass of `RSAbstractCPController`
