### ISSUE TITLE
UML menu

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/Roassal3#344]
From discord @astares 

```
What would be nice would be to have a right click context menu on the UML class shape also in the UML view (same menu as in Calpyso on a class) or to jump to/browse another class on doubleclicking the shape
Without trying I guess it would allow for more easy navigation / switching between classes in same hierarchy.
````

**Comment by akevalion** [comment]
You have these interactions in the last version of uml

With left click you have
![image](https://user-images.githubusercontent.com/10532890/117829078-6958a400-b240-11eb-9f9f-feca24da0dd2.png)

And with double click you can browse the current class

**Comment by astares** [comment]
Nice!
