### ISSUE TITLE
UML selection configuration

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/Roassal3#345]
From discord

Pavel: dancing UML
![dTtMJTiqbU](https://user-images.githubusercontent.com/10532890/115473532-e4163c80-a209-11eb-8442-9b2e8f737677.gif)

Alexandre Bergel — hoy a las 14:26
Yes, this is the way we indicate the class that is currently selected
Maybe not the best way, but it does the job
Pavel — hoy a las 14:26
ahhh :smile:
Alexandre Bergel — hoy a las 14:27
maybe a marker would be better
Pavel — hoy a las 14:28
...or make a setting for it

astares — hoy a las 15:35
@Alexandre Bergel / @Pavel 
Maybe a more darker (more orange) color compared to the light yellow to highlight?
![image](https://user-images.githubusercontent.com/10532890/115473640-0e67fa00-a20a-11eb-89e9-0e9c307881d9.png)

or blue one like the selection in the class pane
![image](https://user-images.githubusercontent.com/10532890/115473668-23448d80-a20a-11eb-9eb8-d27fd6ff2007.png)

**Comment by pavel** [comment]
@akevalion Thanks for notifying me, but it does not seem that I'm involved in this project in any way.

https://blog.github.com/2011-03-23-mention-somebody-they-re-notified/

**Comment by alexandre** [comment]
I neither.
