### ISSUE TITLE
Infinite recursion of RSClusterLayout

### ISSUE THREAD

**Issue by TiredFalcon** [ObjectProfile/Roassal3#348]
Pharo 8.0, Roassal3 0.9.7b. Possibly related to #326.

When using a `RSClusterLayout` on a set of nodes that are connected with a cycle, the algorithm goes in an infinite loop. Specifically, with an user interrupt I see a recursive call of `RSClusterLayout>>initializeNode:`:

```smalltalk
children do: [ :e | self initializeNode: e.
						self fatherOf: e put: aNode ].
```

I would expect the layout to throw an error because a cycle is found, like other layouts such as `RSTreeLayout` do.

Example code causing the infinite recursion:

```smalltalk
c := RSCanvas new.
nodes := RSEllipse models: (1 to: 3) size: 20.
edges := RSLineBuilder arrowedLine
	canvas: c;
	attachPoint: RSBorderAttachPoint new;
	shapes: nodes;
	connectFrom: [ :each | ((each + 1) % 3) + 1 ].
nodes add: (RSEllipse new model: 4; size: 20).

c addAll: nodes.
c add: (RSArrowedLine new withBorderAttachPoint from: nodes last; to: nodes third).

RSClusterLayout on: nodes.
c open.
```

**Comment by TiredFalcon** [comment]
This also happens in the latest Pharo 9.0 version.

**Comment by akevalion** [comment]
I will check this

**Comment by TiredFalcon** [comment]
Thank you!
