### ISSUE TITLE
Issue with the SVG exporter?

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#351]
From botwhytho:
In roassal 2, I was able to export to SVG a couple of the SVG examples, but not other types of examples. Can this exporter be used for trivial Roassal views or only for ones that are built from SVG primitives from the beginning?
Unrelated, a lot of potential culprits, but with the SVG export from above in Pharo 9 (https://discord.com/channels/223421264751099906/300020095844089856/844317570513371166) I tried to import again back into the image by running RSSVGImporter fromString: (taken from example at https://discord.com/channels/223421264751099906/300020095844089856/839252357682298900) but that only works in Pharo 8. When I did import it, the colors were off and I couldn't see the numbers. Strangely enough, after passing that svg through an SVG optimizer tool (https://github.com/svg/svgo) the colors are correct, but still can't see the numbers. Not sure if these are known bugs in importer, but posting here just in case

**Comment by akevalion** [comment]
> In roassal 2, I was able to export to SVG a couple of the SVG examples, but not other types of examples. Can this exporter be used for trivial Roassal views or only for ones that are built from SVG primitives from the beginning?

Roassal2 exporter writes with smalltalk shapes from roassal2. for each shape the exporter defines a command. then is used for trivial roassal view.

> Unrelated, a lot of potential culprits, but with the SVG export from above in Pharo 9 (https://discord.com/channels/223421264751099906/300020095844089856/844317570513371166) I tried to import again back into the image by running RSSVGImporter fromString: (taken from example at https://discord.com/channels/223421264751099906/300020095844089856/839252357682298900) but that only works in Pharo 8. When I did import it, the colors were off and I couldn't see the numbers. Strangely enough, after passing that svg through an SVG optimizer tool (https://github.com/svg/svgo) the colors are correct, but still can't see the numbers. Not sure if these are known bugs in importer, but posting here just in case

SVG Importer works with Athens-SVG, if there is some issue with the importer process that project is where we should submit an issue, also the culprit of only load the importer in pharo8 is XML parser

https://github.com/pharo-contributions/Athens-SVG
https://github.com/pharo-contributions/XML-XMLParser/issues/2

**Comment by bergel** [comment]
So?

**Comment by akevalion** [comment]
I have evaluate this, and yes there is an error with the importer then I move the issue to Athens-SVG
