### ISSUE TITLE
Stacked bar plot does not work

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/Roassal3#353]
From discord

> I think there is a bit of a problem (perhaps) with the Roassal3 example for stacked bar charts (both vertical and horizontal). Specifically example04VerticalStack. It should take two collections of data points and return a "stacked" graph. Instead, it simply draws one bar on top of the other. e.g., for data point 4, menmeans has a value of 35 and womenmeans has a value of 20, but the total height of the bar is 35 instead of 55. It seems to me the problem originates in computeRectagleFor: index: (it's a tiny thing, but probably that needs an extra "n" to make it computeRectangleFor: index:). Not actually sure how to do a stacked bar chart at the moment. Thanks.

**Comment by akevalion** [comment]
> In fact, if I just add the line: aPoint setX: aPoint x setY: (aPoint y + zero).  to computeRectagleFor: index:, which just alters the given point by increasing its y by the correct bottom index through using zero, the whole things works. But that seems a slightly crude "fix".

**Comment by akevalion** [comment]
It is working now `example04VerticalStack`

![image](https://user-images.githubusercontent.com/10532890/119004726-ce0cb080-b95c-11eb-9a08-85fc3760bd71.png)




![image](https://user-images.githubusercontent.com/10532890/119004758-d5cc5500-b95c-11eb-8b85-108f0b7b9895.png)

**Comment by tsl4** [comment]
Thanks so much. Looking forward to looking at the solution. Very much enjoying Roassal!

**Comment by akevalion** [comment]
@bergel can we close this issue?
