### ISSUE TITLE
Optionally keep size of borders or arrows independently of camera zoom

### ISSUE THREAD

**Issue by tinchodias** [ObjectProfile/Roassal3#36]
Sometimes the size of arrows or borders doesn't represent a metric but only the fact that two nodes are connected with some direction. In these cases, I would like to have borders and arrows with a determined size:

<img width="704" alt="image" src="https://user-images.githubusercontent.com/3044265/56832388-de173c00-6839-11e9-8bf1-4387913a9790.png">

And, even if camera has  zoom like here, keep the same size-in-screen:
<img width="704" alt="image" src="https://user-images.githubusercontent.com/3044265/56832379-d48dd400-6839-11e9-86e1-3c4d59555cf0.png">

**Comment by akevalion** [comment]
We have two new interactions for this issue
![image](https://user-images.githubusercontent.com/10532890/57685550-25594700-7606-11e9-8d5f-85d5857b9372.png)

![image](https://user-images.githubusercontent.com/10532890/57685579-32763600-7606-11e9-9ce6-db09f71700de.png)

```Smalltalk
	| v sb label box |
	v := RSView new.
	label := RSShapeBuilder label.
	box := RSShapeBuilder box
		border: TSBorder new;
		cornerRadius: (TSCornerRadius new right: 10);
		extent: [ :lb | lb extent + 5 ].
	sb := RSShapeBuilder composite
		interactionDo: #draggable;
		shapes: [ :m | | l |
			l := label elementOn: m.
			TSGroup with: (box elementOn: l) with: l].
	v addAll: (sb elementsOn: ArrayedCollection withAllSubclasses).
	v @ RSControlsView.
	RSEdgeBuilder orthoHorizontal
		markerEnd: (TSMarker new 
			offsetRatio: 0.1;
			shape: (RSShapeBuilder triangle 
				color: Color red;
				size: 10;
				element));
		attachPoint: RSHorizontalAttachPoint new; 
		border: (TSBorder new);
		view: v;
		elements: v elements;
		connectFrom: #superclass.
	"v edges @ RSKeepBorderWidthRatio. Not necessary since all edges shares the same border"
	
	v edges first @ RSKeepBorderWidthRatio. 
	v edges first @ RSKeepMarkersSizeRatio.
	RSHorizontalTreeLayout new on: v elements.
	v open setLabel: 'Horizontal Tree'
```

This interactions allow to the elements keep the same size. The name of this new classes can be renamed to better names

![image](https://user-images.githubusercontent.com/10532890/57685779-9b5dae00-7606-11e9-99ab-80c1423519ec.png)

**Comment by tinchodias** [comment]
Great, I will check it.

**Comment by bergel** [comment]
Looks very good!
@tinchodias I am okay with closing this issue. What do you think?

**Comment by tinchodias** [comment]
Now that I see how it looks, I'd like to have this effect only when user zooms in but not when you zoom out (arrows become too large). Milton told me this was easy to do. 

Also, the use case where I wanted this feature is Hunter, where the nodes have no text... I think it will look good there.

**Comment by bergel** [comment]
@akevalion Can you check please?

**Comment by tinchodias** [comment]
Now I think we can close this issue.

**Comment by tinchodias** [comment]
Doing it...

**Comment by akevalion** [comment]
There is a new max and min value for this kind of interactions 
- RSKeepBorderWidthRatio
- RSKeepMarkersSizeRatio

**Comment by akevalion** [comment]
There is a maxScale and minScale for RSKeepMarkersSizeRatio and RSKeepBorderWidthRatio
