### ISSUE TITLE
Inspector on pharo3?

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/Roassal3#4]
How can we handle the inspector if glamour is going to be obsolete

**Comment by bergel** [comment]
We should be able to do something like:
`view inspectorContext: (RSContext new expandInspectorOnlyFor: myClasses; for: Class visualize: [ :cls | self visualizeClass: cls ] )`

**Comment by akevalion** [comment]
We have this code with the actual pharo inspector
![image](https://user-images.githubusercontent.com/10532890/62665710-40f69400-b94e-11e9-865e-ea18ccffef3b.png)

![image](https://user-images.githubusercontent.com/10532890/62665807-93d04b80-b94e-11e9-87bc-ae411edc5fe0.png)

![image](https://user-images.githubusercontent.com/10532890/62665815-9f237700-b94e-11e9-9216-b9fb22c9d5c3.png)

![image](https://user-images.githubusercontent.com/10532890/62665835-b1051a00-b94e-11e9-8ce1-8ad8f273329a.png)

The inspector works on the next classes, RSView, TSCanvas, TSShape, RSElement, RSEdge, TSInterpolator.

**Comment by bergel** [comment]
Looks amazing!

**Comment by akevalion** [comment]
I think that we can close this issue
