### ISSUE TITLE
RSBoundingShape>>computeEncompassingRectangleFor:matrix: removed but still used

### ISSUE THREAD

**Issue by SergeStinckwich** [ObjectProfile/Roassal3#408]
Apparently : ``RSBoundingShape>>computeEncompassingRectangleFor:matrix:``
has been removed by commit: 
https://github.com/ObjectProfile/Roassal3/commit/2a9366e690244703251b7f8310152ddf98c772d9#diff-0d926732eee031954909dd744251d64f4e58b548cbaa0328ff4a54317c8fad9c

but this still used in:
``RSBoundingShape>>computeEncompassingRectangleFor: rect 
	^ self computeEncompassingRectangleFor: rect matrix: self matrix``

**Comment by hernanmd** [comment]
It could be loaded by manually loading the Roassal 3 full version from the World menu, but it seems to be that the "full" group currently defined in the Baseline does not load the "Core" where the method computeEncompassingRectangleFor:matrix: is defined.
 
I don't know if it is on purpose. This is the current definition of groups:

```smalltalk
...
        group: 'Mini' with: #('SVGTests' 'SVGExamples');
        group: 'Full' with: #('Mini'), self extraPackagesNames;
        group: 'GraphViz' with: #('Full' 'Roassal3-GraphViz');
        group: 'default' with: #('Core' 'Mini')
```

**Comment by akevalion** [comment]
@hernanmd The group `Full` uses `Mini` and uses group `SVGTests` that group uses `Core`

@SergeStinckwich I will review this in windows 10 with the loading menu from the world menu.

**Comment by akevalion** [comment]
computeEncompassingRectangleFor:matrix: has been moved to RSShape, then this methos is also available for RSLines

**Comment by hernanmd** [comment]
The MNU appears after opening a Roassal canvas in CORMAS (specifically the Space Interface). We have this in our Baseline:

```smalltalk
     spec baseline: 'Roassal3' with: [ spec repository: 'github://ObjectProfile/Roassal3'; loads: 'Full' ];
```

It seems that the method computeEncompassingRectangleFor:matrix: was loaded by the script in the world menu, but not with that baseline expression.

**Comment by akevalion** [comment]
I have test it with different repositories, for example https://github.com/ObjectProfile/HierarchicalVisualizations
and I do not have the MNU

**Comment by akevalion** [comment]
@SergeStinckwich is this issue still valid?

**Comment by akevalion** [comment]
I will close this issue
