### ISSUE TITLE
We need Spy for roassal3

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/Roassal3#41]

**Comment by akevalion** [comment]
Add a tag for ObjectProfile/Spy2

**Comment by akevalion** [comment]
Here some update
https://github.com/ObjectProfile/Spy2 uses Roassal3 here some screenshots

![image](https://user-images.githubusercontent.com/10532890/59387175-82940580-8d36-11e9-8f15-8ac77feb12bb.png)

TODO remove all references from roassal2 in spy2

**Comment by akevalion** [comment]
There is a new version of hapao, with:

- the menus fixed, al menu items in world menu works.
- Support for dark theme.
- new legend with animated logos.
- new about window.
- new button "profile it again"
- new hight light interaction an status bar of each class

![image](https://user-images.githubusercontent.com/10532890/60198655-20e09a80-9810-11e9-8259-c2d806849515.png)

Next issues report it on https://github.com/ObjectProfile/Spy2

**Comment by bergel** [comment]
Seems to works, but something is weird with the loading...
