### ISSUE TITLE
Red screen of death related with globalMatrix and missing canvas

### ISSUE THREAD

**Issue by hernanmd** [ObjectProfile/Roassal3#410]
The bug is related with RSAthensMorph drawing and the method globalMatrix is not understood. It could be reproduced by [installing CORMAS in a Pharo 9 image](https://github.com/cormas/cormas/#standard-installation), and following the directions of [this video](https://youtu.be/u3NIiorplQc)

(note that at the beginning the Full version of Roassal 3 is loaded from the World menu)

**Comment by akevalion** [comment]
I will review this

**Comment by akevalion** [comment]
I got the red screen
![image](https://user-images.githubusercontent.com/10532890/128740678-8757185a-5074-42f4-9062-822ae6b73362.png)

**Comment by akevalion** [comment]
done can you review if this is fixed?

**Comment by hernanmd** [comment]
So far I couldn't reproduce it anymore so it could be closed.
Thanks
