### ISSUE TITLE
Enable unattended loading of Roassal 3 from world menu

### ISSUE THREAD

**Issue by hernanmd** [ObjectProfile/Roassal3#411]
Loading the Full version of Roassal from the world menu in Pharo 9 generates multiple confirm dialogs with text like the following: "You are about to load new versions of the following packages that have unsaved changes in the image:    Roassal3-Interaction  If you continue, you will lose these changes:"

Enable loading the full version of Roassal 3 in unattended mode (without confirm dialogs) from the World menu item.

**Comment by akevalion** [comment]
I have updated the script for the full version of roassal from world menu
now uses this script

```smalltalk
[Metacello new
    baseline: 'Roassal3';
    repository: 'github://ObjectProfile/Roassal3';
    load: 'Full' ] on: MCMergeOrLoadWarning do: [:warning | warning load ]

```

**Comment by hernanmd** [comment]
Thank you @akevalion
