### ISSUE TITLE
#reset methods should be in initialization protocol

### ISSUE THREAD

**Issue by gypsydave5** [ObjectProfile/Roassal3#418]
Hi! 👋 - see https://github.com/pharo-project/pharo/issues/2607, which this unblocks. Hope this makes sense. PR incoming!

**Comment by gypsydave5** [comment]
Not sure if this should be changed in master or in a branch to affect the P10 image.

**Comment by akevalion** [comment]
I have moved reset methods to initialization protocol

**Comment by akevalion** [comment]
Done
