### ISSUE TITLE
Padding between the window border and inner figures (zoomToFit)

### ISSUE THREAD

**Issue by hernanmd** [ObjectProfile/Roassal3#420]
Using Pharo 9.0 it seems #zoomToFit does not really zoom to fit inner figures to the window borders.
Consider the following code:

```smalltalk
| c |
c := RSCanvas new.
blueBox := RSBox new
              size: 80;
              color: #blue.
redBox := RSBox new
              size: 80;
              color: #red.
c
    add: blueBox;
    add: redBox.
blueBox translateBy: 40 @ 20.
c zoomToFit.
c open.
```

This produces the output:
![Screen_Shot_2021-09-21_at_11 12 02_PM](https://user-images.githubusercontent.com/4825959/134396406-da23055d-37e7-42d7-b184-6ea09d4cb711.png)

But a precise fit would produce:

![Screen_Shot_2021-09-21_at_11 12 56_PM](https://user-images.githubusercontent.com/4825959/134396498-31bc4618-04b0-43fd-a506-4fc1a02ba923.png)

**Comment by akevalion** [comment]
Hi Hernan, zoomToFit uses a the camera's zoomToFit, then you can use:

```Smalltalk
| c |
c := RSCanvas new.
blueBox := RSBox new
              size: 80;
              color: #blue.
redBox := RSBox new
              size: 80;
              color: #red.
c
    add: blueBox;
    add: redBox.
blueBox translateBy: 40 @ 20.
c when: RSExtentChangedEvent do: [ 
	c camera zoomToFit: c extent.
	c signalUpdate. ].

c open.
```

Use the event to always have the zoomToFit behavior, when the canvas changes its extent

**Comment by hernanmd** [comment]
Thanks Milton. I tried and it works for Roassal3 canvas, however it doesn't work when the canvas is inside a Spec2 window, like for example a subclass of SpRoassalPresenter. I will keep trying and let you know if I find something.

**Comment by akevalion** [comment]
@hernanmd is this issue still valid? let me know if I can help you

**Comment by akevalion** [comment]
I have test it with a presenter and it works for me

```st
presenter := SpRoassalPresenter new.
blueBox := RSBox new
              size: 80;
              color: #blue.
redBox := RSBox new
              size: 80;
              color: #red.
presenter canvas
    add: blueBox;
    add: redBox.
blueBox translateBy: 40 @ 20.
presenter canvas when: RSExtentChangedEvent do: [ :evt |
	evt camera zoomToFit: evt canvas extent.
	evt signalUpdate. ].
presenter open.
```

<img width="441" alt="image" src="https://user-images.githubusercontent.com/10532890/195839992-05992f4e-f67d-4f3f-b648-72702ad70d17.png">
