### ISSUE TITLE
RSPopup: can't customize the background color of the popups

### ISSUE THREAD

**Issue by tinchodias** [ObjectProfile/Roassal3#423]
This is the key method:
```
RSSimplePopupBuilder
>>
boxFor: lbl
	^ RSBox new
		color: (Color colorFrom: 'efefef');
		cornerRadius: 5;
		border: (RSBorder new color: Color gray);
		extent: lbl extent + (10@7);
		yourself
```

**Comment by tinchodias** [comment]
I think that a possible solution is replicating interesting box parameters in the builder, but it's preferable to have a single `boxFactoryBlock` lazy inst var/method like: 

```
boxFactoryBlock

   ^ boxFactoryBlock ifNil: [
         boxFactoryBlock := [
            RSBox new
		color: (Color colorFrom: 'efefef');
		cornerRadius: 5;
		border: (RSBorder new color: Color gray);
		extent: lbl extent + (10@7);
		yourself 
    ] ]
```

**Comment by tinchodias** [comment]
But probably there is a "Roassal style" to fix this consistently with other situations where this happens.

**Comment by akevalion** [comment]
I have added a new class `RSSimpleBoxBuilder ` and new example `example46Popups`

![image](https://user-images.githubusercontent.com/10532890/141936638-a2dfc247-6414-4ee4-ae07-4c6d31e6d97b.png)
