### ISSUE TITLE
Add flame graph to baseline

### ISSUE THREAD

**Issue by tinchodias** [ObjectProfile/Roassal3#424]
We added 2 packages last week but they are  ignored by baseline for the moment.

To which group should add them?

**Comment by akevalion** [comment]
I have added FlameGraph to the baseline, to added a new one, check these methods

- corePackagesNames
- examplePackagesNames
- testPackagesNames
- extraPackagesNames

**Comment by tinchodias** [comment]
Great,  thanks! it simplifies loading it a lot.

**Comment by akevalion** [comment]
@bergel  can we close this issue?
