### ISSUE TITLE
RSSunburstBuilder: Customize popup and disable draggablility?

### ISSUE THREAD

**Issue by tinchodias** [ObjectProfile/Roassal3#426]
This is the key method:

```
shapeFor: anObject
	| slice |
	slice := self sliceShape copy
		model: anObject;
		popup;
		draggable;
		yourself.
	slice color: (color rsValue: slice).
	^ slice 
```

I guess:
- "draggable" can be removed
- "popup" may also be removed, or just send value to a block closure in a instvar, or directly having the RSPopup instance.

What do you think?

**Comment by akevalion** [comment]
users should define the use of popup or draggable or other interaction

**Comment by tinchodias** [comment]
Thanks

**Comment by akevalion** [comment]
@bergel could we please close this issue

consider this example

```st
| sb |
sb := RSSunburstBuilder new.
sb explore: Collection using:  #subclasses.
sb canvas @ RSCanvasController.
sb open
```
will create a sunburst in a window

<img width="435" alt="image" src="https://user-images.githubusercontent.com/10532890/166641648-4b638b06-cc7b-4128-953f-292f0f55cf01.png">

Now consider the following example to add interaction and new elements
```st
| sb |
sb := RSSunburstBuilder new.
sb explore: Collection using:  #subclasses.
sb canvas @ RSCanvasController.
sb build.
sb shapes @ RSPopup.
RSLineBuilder arrowedLine
	attachPoint: RSSunburstAttachPoint new;
	canvas: sb canvas;
	connectFrom: #superclass.
sb canvas open
```

Then is this issue still valid?
