### ISSUE TITLE
Layout that holds its shapes inside

### ISSUE THREAD

**Issue by NourDjihan** [ObjectProfile/Roassal3#429]
<img width="726" alt="Screenshot 2021-11-24 at 14 18 53" src="https://user-images.githubusercontent.com/34944559/143245776-863be81e-8c23-49ef-acd8-f265d9a58b9d.png">
I am having a problem fixing the shapes inside the layout and not out. I could use comme configurations but the configurations might not work for all cases.

**Comment by akevalion** [comment]
Is this issue still valid? if no, could you please explain the expected result/behavior of roassal3

**Comment by akevalion** [comment]
As I saw your code https://github.com/NourDjihan/ClassBlueprint I think we can close this issue, 
If I remember correctly, this was an issue to create a configurable layout based on constraints. Something like a group layout, but that can be a new issue, if you have the requirements
