### ISSUE TITLE
Remove Obsolete Spec1 package from default download

### ISSUE THREAD

**Issue by guillep** [ObjectProfile/Roassal3#431]
corePackagesNames
	^ #(
	'Roassal3-Event'
	'Roassal3-Builders'
	'Roassal3-Shapes'
	'Roassal3-Animation'
	'Roassal3-Interaction'
	'Roassal3-Layouts-Util'
	'Roassal3-Layouts'
	'Roassal3-Colors'
	'Roassal3-Legend'
	'Roassal3-UML'
	'Roassal3-Sunburst'
	'Roassal3-Pie'
	'Roassal3-Inspector'
	'Roassal3-Chart'
	'Roassal3-Menu'
	'Roassal3-Spec'
	'Roassal3-Spec-Morphic'
	)

**Comment by akevalion** [comment]
I have removed dependencies from Roassal3 to Spec1. It should be visible when Pharo accepts the pull request to version v0.9.9d

**Comment by akevalion** [comment]
The pull request is accepted

**Comment by bergel** [comment]
Done!
