### ISSUE TITLE
Loading in Pharo 8 raises error "Name not found: Roassal3-Spec-Obsolete"

### ISSUE THREAD

**Issue by Ironirc** [ObjectProfile/Roassal3#432]
Just tried to load in a virgin Pharo 8 image using: 
Metacello new
    baseline: 'Roassal3';
    repository: 'github://ObjectProfile/Roassal3:v0.9.9d';
    load.

**Comment by akevalion** [comment]
Fixed will be present in the next roassal3 release, for now please use 
```smalltalk
[Metacello new
    baseline: 'Roassal3';
    repository: 'github://ObjectProfile/Roassal3';
    load ] on: MCMergeOrLoadWarning do: [:warning | warning load ]
```

**Comment by Ironirc** [comment]
That works fine, thanks!

**Comment by bergel** [comment]
@Ironirc Let us know if you still experience some issue
