### ISSUE TITLE
Arrow shape in UML: make the triangle equilateral

### ISSUE THREAD

**Issue by tinchodias** [ObjectProfile/Roassal3#44]
I hope I'm not too picky :)
![Screen Shot 2019-06-07 at 15 32 16](https://user-images.githubusercontent.com/3044265/59129116-e931b180-8939-11e9-8cdf-7b1b6cd6480e.png)

**Comment by akevalion** [comment]
The triangle has an extent of `25@25` 
![image](https://user-images.githubusercontent.com/10532890/60690796-33a24180-9e98-11e9-8c02-3485646b2255.png)

**Comment by tinchodias** [comment]
Looks well!
