### ISSUE TITLE
Fix lint: use #ifNotNil: in RSAbstractLine>>#setAnchor:shape:

### ISSUE THREAD

**Issue by astares** [ObjectProfile/Roassal3#448]
There is a new lint rule added in https://github.com/pharo-project/pharo/pull/11261/
to simplify code.

Roassal could be simplified in RSAbstractLine>>#setAnchor:shape: by using #ifNotNil:

![image](https://user-images.githubusercontent.com/5980033/170012620-f3141014-e204-4f0e-903b-b5969e6a61a2.png)

**Comment by akevalion** [comment]
done
