### ISSUE TITLE
RSLabels are not taking starting spaces into account

### ISSUE THREAD

**Issue by pavel-krivanek** [ObjectProfile/Roassal3#457]
The labels have any very nasty behavior - they are skipping spaces at the label beginning of the string and it is not taken into the label measurements in any way.

!! Example

```smalltalk
c := RSCanvas new.
c addShape: (RSLabel text: 'text').
c addShape: (RSLabel text: '    text').
c
```

![image](https://user-images.githubusercontent.com/572494/179179938-3ede48e4-6e6a-4b53-9d1f-a5acc3092bb0.png)

While expected look should be similar to this:

```smalltalk
c := RSCanvas new.
c addShape: (RSLabel text: 'text').
c addShape: (RSLabel text: '____text').
c
```

![image](https://user-images.githubusercontent.com/572494/179180028-be6d48c0-3eb3-4b95-9038-37d402bedd4b.png)

IMHO the RSLabel is not woring with `x_advance` measure correctly.

**Comment by akevalion** [comment]
@pavel-krivanek sorry for the delay of my answer, I am going to review this issue at this moment. I will share my results with you

**Comment by akevalion** [comment]
I have added a change now you should be able to see the change, let me know if works for you
```st

lines := ('
        .--''''''''''''''''''--.
     .''      .---.      ''.
    /    .-----------.    \
   /        .-----.        \
   |       .-.   .-.       |
   |      /   \ /   \      |
    \    | .-. | .-. |    /
     ''-._| | | | | | |_.-''
         | ''-'' | ''-'' |
          \___/ \___/
       _.-''  /   \  `-._
     .'' _.--|     |--._ ''.
     '' _...-|     |-..._ ''
            |     |
            ''.___.''' lines collect: [ :line |
	RSLabel new
		text: line;
		fontName: 'Courier New';
		yourself ]).
RSVerticalLineLayout new gapSize: 0; alignLeft; on: lines.
canvas := RSCanvas new.
canvas add: lines asShape..
canvas showEncompassingRectangles.
canvas zoomToFit.
canvas
```
<img width="467" alt="image" src="https://user-images.githubusercontent.com/10532890/180467661-d8fac993-373e-4541-994c-9824a4122b2d.png">

**Comment by pavel-krivanek** [comment]
we can close it now, rigth?

**Comment by akevalion** [comment]
done
