### ISSUE TITLE
Rename in RSTreeMapLayout >> prepareShapesForLayout: inRectangle:

### ISSUE THREAD

**Issue by NSUSpray** [ObjectProfile/Roassal3#459]
I started gradually reviewing the TreeMap package. It seems to me that some points can be made clearer. Here is my first suggestion:

rename the method
```Smalltalk
RSTreeMapLayout >> prepareShapesForLayout: shapes inRectangle: rec
```
to
```Smalltalk
RSTreeMapLayout >> normalizeAreaOf: shapes byAreaOf: rec
```
Perhaps the time for refactoring hasn’t come yet and I’m running ahead.

**Comment by NSUSpray** [comment]
And I’ll add more, from this point on, the algorithm becomes quite complex (I haven’t been able to figure it out yet). Comments in the code (or a link to an article with explanations) would be useful.

**Comment by akevalion** [comment]
renamed

Hi @NSUSpray I was looking for the original source and creator of this code without look, I can tell you that was created for Roassal1, and worked with Alexandre Bergel, Tudor Girba, Roberto Minelli and Mircea Lungo, but could not find the original code for that. Then no documentation

**Comment by NSUSpray** [comment]
> renamed

Yeah, I saw it after pull. Perhaps the method `prepareShapesForLayout: inRectangle:` was named that way in the expectation of redefinition during inheritance (in case the preparation of shapes will be some other). But personally, I don’t see any reason to prepare the shapes, other than fitting their *areas* by the container.

**Comment by NSUSpray** [comment]
> Hi @NSUSpray I was looking for the original source and creator of this code without look, I can tell you that was created for Roassal1, and worked with Alexandre Bergel, Tudor Girba, Roberto Minelli and Mircea Lungo, but could not find the original code for that. Then no documentation

Thanks for clarifying the origin. I intend to figure out the algorithm, because it seems that the cutting is the most clumsy there (“slice and dice” or something like that), which is why some pieces are too thin. It would be necessary to find somewhere an explanation of this and more advanced algorithms. It is possible that these will be examples from the great d3.js :)

**Comment by akevalion** [comment]
I close the issue because it is completed, for new algorithms we have this issue https://github.com/ObjectProfile/Roassal3/issues/460
