### ISSUE TITLE
UML view (and possibly most views): Set maximum zoom in = 1

### ISSUE THREAD

**Issue by tinchodias** [ObjectProfile/Roassal3#46]
The user doesn't need to see more details on a UML class. Also, given inertia zoom in in Mac is tricky...

This requires that also zoomToFit doesn't goo beyond this zoom limit... should i create a separate issue?

**Comment by tinchodias** [comment]
Additionally, it may help to inertia effect when scrolling in Mac, that the maximum zoom out is equal or close to the level used in zoomToFit. 

For example, here I did scroll out:
<img width="434" alt="Screen Shot 2019-06-25 at 11 37 33" src="https://user-images.githubusercontent.com/3044265/60112358-a47d8700-973d-11e9-9a4c-f0ac56f2e062.png">

And I don't imagine a case where it's useful to see those empty margins... the zoom out should had stop before.

**Comment by akevalion** [comment]
Related to https://github.com/ObjectProfile/Roassal3/issues/45.
Try to use
```Smalltalk
controls := RSControlsView new.
controls configuration useBasicZoom.
```
