### ISSUE TITLE
Chart and plot should be polymorphic

### ISSUE THREAD

**Issue by guillep** [ObjectProfile/Roassal3#466]
We always need to make a chart and add a plot inside.
Why a plot is not a chart or works as a chart?

```smalltalk
chart := RSChart new.
points := RSLinePlot new
	x: dates
	y: values.
chart add: points.
chart ...
chart ...
```

I would expect to write

```smalltalk
chart := RSLinePlot new
	x: dates
	y: values.
chart ...
chart ...
```

**Comment by maxwills** [comment]
Disclaimer. I don't work in Roassal, just have some experience with matplotlib.
I think that Roassal is a general purpose plotting library. It follows some "composable"-"standard" design.
Take a look at this (taken from [here](https://stackoverflow.com/questions/17458580/embedding-small-plots-inside-subplots-in-matplotlib)):
![subplots](https://i.stack.imgur.com/uGaKA.png)
The chart would correspond to the whole figure where you put all your plots (or subplots if you will, like linesplot, histogram, etc). So, to create more fancy or complex visualization, the distinction is necessary in that context.

**Comment by guillep** [comment]
But the plot can behave as a chart, and the chart is a composite only. It's a composite pattern. I'm not saying that Chart should not exist, I'm saying that from a user stand point, it should not be there unless you want to compose them.

**Comment by guillep** [comment]
This was done on https://github.com/ObjectProfile/Roassal3/pull/568
