### ISSUE TITLE
Review default number of ticks

### ISSUE THREAD

**Issue by guillep** [ObjectProfile/Roassal3#467]
Is 20 a sensible default? we should learn from ggplot and matplotlib

```smalltalk
chart add: (RSHorizontalTick new
	numberOfTicks: 20;
        yourself)
```

**Comment by guillep** [comment]
Can this be considered done as per #555, #556, #559?

**Comment by guillep** [comment]
Actually, the locators fix the issue with the positions. @DurieuxPol do they also manage well the default number of ticks?

**Comment by akevalion** [comment]
Closed as done thanks @DurieuxPol
