### ISSUE TITLE
Fix lints for instance side #initialize methods by putting them into "initialization" category

### ISSUE THREAD

**Issue by astares** [ObjectProfile/Roassal3#488]
Some Roassal3 classes have the instance side method #initialize not in the category "initialization"

This is inconsistent with other classes in Roassal3 and the rest of the standard Pharo image where #initialize is in method category "initialization". It could be easily fixed by using the Auto-repair on the lint error that is shown for such issues.

**Comment by astares** [comment]
![image](https://user-images.githubusercontent.com/5980033/203671763-2e6cbad7-fcd8-418b-acc1-239597e6e674.png)

**Comment by akevalion** [comment]
Fixed!
