### ISSUE TITLE
RSAbstractLine uses RSTPositionable, even though position can't be set

### ISSUE THREAD

**Issue by JanBliznicenko** [ObjectProfile/Roassal3#492]
`RSAbstractLine` uses `RSTPositionable`, that provides methods `translateBy:` and `translateTo:`

`translateTo:` method uses `position:` method, but lines do not have it, only nodes (`RSBoundingShape`)

**Comment by akevalion** [comment]
Thank I will review this

**Comment by akevalion** [comment]
Now dual lines and lines with control points define method #position:
