### ISSUE TITLE
Strange behavior with method "from:" and "to:" of RSLine class

### ISSUE THREAD

**Issue by PerlNoire** [ObjectProfile/Roassal3#495]
Hello,

by example if you switch the line 25 
	_parent1 translateTo: 100@100._
by
	_parent2 translateTo: 100@100._
in "example30EdgesToChildren".
The behavior expected is wrong.

**Comment by akevalion** [comment]
I have fix the example.
In this case you can see: `translateTo:` and `position:`, both do the same, change the position shape.
But with some differences.
- `translateTo:` triggers events, and can ignore the new position if it is like the old one.
- `position:` does not trigger events and It does not evaluate if the new position is like the old one.

**Comment by PerlNoire** [comment]
Thanks for your clear explanation. Have a good day.
