### ISSUE TITLE
May be RSAnimationLoopEvent comes too hearly...

### ISSUE THREAD

**Issue by PerlNoire** [ObjectProfile/Roassal3#497]
Hello,

I tryed to make this code work:
----------------------
	| canvas shape radius breatheIn bloc subBloc |
	breatheIn := true.
	subBloc := [ :boolean | 
	           boolean
		           ifTrue: [ [ :t | t ] ]
		           ifFalse: [ [ :t | 1 - t ] ] ].
	bloc := subBloc value: breatheIn.
	radius := 150.
	canvas := RSCanvas new.
	shape := RSEllipse new
		         border: (RSBorder new
				          width: 2;
				          color: 'black';
				          yourself);
		         radius: 0;
		         yourself.
	canvas add: shape.
	canvas newAnimation repeat
		onStepDo: [ :t | 
			| coef |
			coef := bloc value: t.
			shape
				radius: radius * coef;
				color: (Color
						 r: 0
						 g: shape radius
						 b: 0
						 range: 255) ];
		when: RSAnimationLoopEvent do: [ :evt | 
		breatheIn := breatheIn not.
		bloc := subBloc value: breatheIn ].
	canvas open

-------------

if I exclude the last loop it's working:

-------------
	| canvas shape radius breatheIn bloc subBloc |
	breatheIn := true.
	subBloc := [ :boolean | 
	           boolean
		           ifTrue: [ [ :t | t ] ]
		           ifFalse: [ [ :t | 1 - t ] ] ].
	bloc := subBloc value: breatheIn.
	radius := 150.
	canvas := RSCanvas new.
	shape := RSEllipse new
		         border: (RSBorder new
				          width: 2;
				          color: 'black';
				          yourself);
		         radius: 0;
		         yourself.
	canvas add: shape.
	canvas newAnimation repeat
		onStepDo: [ :t | 
			| coef |
			t == 1 ifFalse: [ 
					coef := bloc value: t.
					shape
						radius: radius * coef;
						color: (Color
								 r: 0
								 g: shape radius
								 b: 0
								 range: 255) ] ];
		when: RSAnimationLoopEvent do: [ :evt | 
		breatheIn := breatheIn not.
		bloc := subBloc value: breatheIn ].
	canvas open

-------

**Comment by PerlNoire** [comment]
Patch suggested to fix this issue. (If it's a real issue because I don’t know if the initial behavior was desired).

Before:
----------------------
RSTransitionAnimation>>progress 
	| progress |
	self startStep.
	progress := (self currentTime - pauseTime - startLoopTime)/ duration asFloat.
	progress > 1 ifTrue: [ 
		self loopDone.
		progress := 1.
		 ].
	
	^ progress


RSTransitionAnimation>>step 
	| value |
	value := self progressValue: self progress.
	stepAction cull: value.
	self updateHasCompleted



Path:
----------------------

RSTransitionAnimation>>progress 
	| progress |
	self startStep.
	progress := self currentTime - pauseTime - startLoopTime
	            / duration asFloat.
	progress := progress min: 1.

	^ progress


RSTransitionAnimation>>step 
	| value |
	value := self progressValue: self progress.
	stepAction cull: value.
	value == 1 ifTrue: [self loopDone].
	self updateHasCompleted

----------------------

Best regards.

**Comment by akevalion** [comment]
I will review it

**Comment by akevalion** [comment]
Fixed, I have included your changes, thank you very much.
Also you can perform a pull request :-)

**Comment by PerlNoire** [comment]
Thanks. It's ok know but I saw that RSAbstractExamples>>example19Stars no longer works properly now.
I will create a new issue and will propose you a fix patch.
