### ISSUE TITLE
Bug method repeat of RSTransitionAnimation when to: method used

### ISSUE THREAD

**Issue by PerlNoire** [ObjectProfile/Roassal3#498]
Hello,
RSAbstractExamples>>example19Stars no longer works properly. 

Patch proposed to fix this issue.

Before
---------
RSTransitionAnimation>>step
| value |
value := self progressValue: self progress.
stepAction cull: value.
value == 1 ifTrue: [self loopDone].
self updateHasCompleted
---------

Patch:
---------
RSTransitionAnimation>>step
	| value progress  |
	progress := self progress.
	value := self progressValue: progress.
	stepAction cull: value.
	progress == 1  ifTrue: [self loopDone].
	self updateHasCompleted
-------

Regards.

**Comment by akevalion** [comment]
Accepted, thank you for the feedback
