### ISSUE TITLE
Make Roassal3 Spec friendly

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#5]
Here is a starting point

[Diagram-Editor-UI.st.txt](https://github.com/ObjectProfile/Roassal3/files/2946961/Diagram-Editor-UI.st.txt)

**Comment by akevalion** [comment]
We have a new version of Roassal3 with spec

![image](https://user-images.githubusercontent.com/10532890/59883325-a7b1f500-9382-11e9-8fc2-a96b55ac7c52.png)

**Comment by akevalion** [comment]
I think we can close this issue
