### ISSUE TITLE
RSAbstractTick crashes when creating a bar plot with only one value

### ISSUE THREAD

**Issue by jordanmontt** [ObjectProfile/Roassal3#500]
When creating a bar plot that has only one value, the ticks are updated like this:

```st
RSAbstractTick>>fromNames: aCollectionOfStrings
	self
		doNotUseNiceLabel;
		numberOfTicks: aCollectionOfStrings size-1.
```

So, as `aCollectionOfStrings size` is one, the value is set to 0 which produces an exception in the debugger 

<img width="967" alt="Capture d’écran 2023-01-16 à 13 59 47" src="https://user-images.githubusercontent.com/33934979/212683954-66cd36f9-1e19-405a-af6e-7227b2ddf3cc.png">

**Comment by akevalion** [comment]
I have created a control in `fromNames:`.
But I think this is something that is not totally clear in roassal chart library. A todo for a new chart library based on
https://github.com/sambegou122/DLPoster
mathplotlib and ggplot
