### ISSUE TITLE
RSMultilineLabelBuilder with RSWrapStrategy produces empty lines

### ISSUE THREAD

**Issue by JanBliznicenko** [ObjectProfile/Roassal3#503]
When `RSMultilineLabelBuilder` is used with `RSWrapStrategy` and there is long word (continuous text without spaces) that has to split into more than 3 lines, all such split lines except of last 3 contain an empty line after each one.

This will be usually very rare, of course, and it will be rare even in my use case. It's just that I found this out while testing with long continuous string.

![obrazek](https://user-images.githubusercontent.com/9571633/217791605-5941c3ff-8fbc-4fe9-ad87-266ba70f0405.png)
![obrazek](https://user-images.githubusercontent.com/9571633/217794226-48e1255b-5569-4341-9ad9-8c394f414688.png)

```
canvas := RSCanvas new.

labelBuilder := RSMultilineLabelBuilder new.
labelBuilder wrapStrategy:
		(RSWrapStrategy new wrapMaxWidth: 100).

label := labelBuilder shapeFor: 'abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz'.

canvas add: label.

canvas open.
```

Or the alternative string: `'abc def ghi jkl mno pqr stuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzab cde fgh ijk lmn opq rst uvw xyz'`

**Comment by akevalion** [comment]
hello tomorrow I will work on this issue
