### ISSUE TITLE
UML collapse and expand icon: keep top & left position

### ISSUE THREAD

**Issue by tinchodias** [ObjectProfile/Roassal3#51]
It's not practical that when you collapse a class, it moves position and then you have to move mouse to expand it again. Also it breaks layout.

**Comment by akevalion** [comment]
Roassal3, is now using the default font of the pharo system.

This is affect to each instance of TSLabel. 
![image](https://user-images.githubusercontent.com/10532890/62242444-2d28bc00-b3a9-11e9-8cc2-292e011440f9.png)

**Comment by akevalion** [comment]
I have removed the method collapse and expand
