### ISSUE TITLE
In Pharo 9 after updating to latest version of Roassal3 the 1st example provided in Roassal3Documentation is not working

### ISSUE THREAD

**Issue by aleksandarhorvat** [ObjectProfile/Roassal3#520]
This [example](https://github.com/ObjectProfile/Roassal3Documentation/blob/master/documentation/Chart.md#simple-example) is not working in Pharo 9 after updating to latest version of Roassal3.

**Comment by akevalion** [comment]
I have fixed baseline for pharo9.
