### ISSUE TITLE
RSCamera>>#position: has inverted effect

### ISSUE THREAD

**Issue by JanBliznicenko** [ObjectProfile/Roassal3#523]
Using #position:, #translateBy: and #translateTo: on RSCamera produces same result as if the given coordinates were negated.

v0.9.9m was acting according to class comment of RSCamera, but latest commit (732803e) is not.

If you run following code:
```Smalltalk
|c|
c := RSCanvas new.
c add: (RSEllipse new).
c camera translateBy: 150 @ 100.
c open.
```

it has different effect between the two commits.

It breaks camera setters, like RSZoomToShapesSetter:
```Smalltalk
|c|
c := RSCanvas new.
c add: (RSEllipse new translateBy: 100@100).
RSZoomToShapesSetter new canvas: c; set: [  ].
c open.
```
As you can notice, the ellipse is not in the center, but even further from it that it was without using the setter.

**Comment by akevalion** [comment]
Hi after version 1.0 the last version in master has a new coordinate system.
Users now can use
```st
canvas originTopLeft.
"or"
canvas originCenterMiddle.
```

**Comment by JanBliznicenko** [comment]
Yes, I believe I fixed the CamSetter, so that should be ok now.

The thing is that originally, `canvas camera translateBy: 100@100` moved shapes to the top left and now it moves shapes to the bottom right (I mean move relatively to the window/morph). That is quite big API change and is one of the reasons CamSetter broke (it was moving the camera in the opposite direction).

I am not aware of any more broken stuff in code because of that, just that RSCamera class comment still has the original description of position that is no longer true: "position is a point representing coordinates of the canvas on which the viewing window frame will be centered"

**Comment by akevalion** [comment]
Is fixed with your pr
