### ISSUE TITLE
We need RSHighlightable with animated edges

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/Roassal3#53]
Hapao/Spy2 has a nice interaction that animated the direction of edges, move that behavior to roassal

**Comment by akevalion** [comment]
RSHighlightable now has the method, setupAntAnimation

```Smalltalk
	shape := RSShapeBuilder composite
		color: Color white trans;
		interactionDo: [:i | 
			| high label |
			label := RSLabeled new.
			label shape color: Color white.
			high := RSHighlightable new.
			high setupAntAnimation.
			i popupAndDraggable; addInteraction: label; addInteraction: high ];
```


![image](https://user-images.githubusercontent.com/10532890/60690614-b2967a80-9e96-11e9-91b4-1bfcb30c1cb9.png)

check `example29AntAnimation`to get the full version of the example

**Comment by bergel** [comment]
Well done!
