### ISSUE TITLE
Easel

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#54]
- Should be accessible from the world menu
- Be aware of the theme
- have `view @ RSControlsView` per default. But this should be parametrizable.
- `view` and `canvas` should be properly highlighted
- The code text panel should be hiddable 
- The code text panel should be resizable
- Cmd-g should work
- the `self` variable should be bound to an object.

**Comment by bergel** [comment]
I have issues when trying to zoom in the easel using I and o

**Comment by akevalion** [comment]
Update
- Now is accessible from the world menu.
- the canvas changes the background according to the theme.
- RSCanvasController is accessible to be parametrizable.
- The code text panel is resizable

Missing requirements
- `canvas` should be properly highlighted
- The code text panel should be hiddable
- Cmd-g should work
- the self variable should be bound to an object.

**Comment by tinchodias** [comment]
After trying and failing to fix the "canvas should be properly highlighted" item, I think it's a Spec2 bug. But it was Pharo8's Spec2, no idea in latest commits.

**Comment by tinchodias** [comment]
It is a feature supported in Glamour and Rubric but not in Spec2.

**Comment by akevalion** [comment]
I think now RSEasel is kind of example for roassal, then could we close this issue or do we need to work more with RSEasel?
