### ISSUE TITLE
Default size of axis titles should not be much bigger than tick lables

### ISSUE THREAD

**Issue by olekscode** [ObjectProfile/Roassal3#544]
Here is an example
```st
example10BarPlot
	<script: 'self new example10BarPlot open'>
	| c p x y |

	x := 0.0 to: 2 count: 10.
	y := (x raisedTo: 2) - 2.
	c := RSChart new.
	p := RSBarPlot new x: x y: y.

	c addPlot: p.

	c addDecoration: (RSHorizontalTick new
		doNotUseNiceLabel;
		numberOfTicks: x size - 1;
		asFloat).
	c xlabel: 'X Axis'.
	c addDecoration: (RSVerticalTick new
		numberOfTicks: 10;
		asFloat).
	c ylabel: 'Y Axis'.
	c title: 'Histogram'.
	^ c
```
<img width="561" alt="image" src="https://github.com/ObjectProfile/Roassal3/assets/8271691/3eb4bf5c-7867-4b9b-9edb-4b33a22234e3">

The default axis titles (X axis and Y axis) are way too large.
Compare this to the ggplot. Axis titles have same size as tick labels - but slightly different colors. And it looks great!

<img width="681" alt="image" src="https://github.com/ObjectProfile/Roassal3/assets/8271691/b21cfe6d-446b-4a68-8529-a45b400cc4d2">

<img width="689" alt="image" src="https://github.com/ObjectProfile/Roassal3/assets/8271691/a279d78e-c292-48dc-b0bc-f6423f153433">

**Comment by akevalion** [comment]
Update
```st
| p x y |

	x := 0.0 to: 2 count: 10.
	y := (x raisedTo: 2) - 2.
	p := RSBarPlot new x: x y: y.

	p horizontalTick doNotUseNiceLabel;
		numberOfTicks: x size - 1;
		asFloat.
	p xlabel: 'X Axis'.
	p verticalTick numberOfTicks: 10;
		asFloat.
	p ylabel: 'Y Axis'.
	p title: 'Histogram'.
	^ p
```
<img width="471" alt="image" src="https://github.com/ObjectProfile/Roassal3/assets/10532890/1a57342e-f597-425f-abdc-79ff3b3c966a">
