### ISSUE TITLE
UML builder layout: align sole child

### ISSUE THREAD

**Issue by tinchodias** [ObjectProfile/Roassal3#55]
(when it's the only children)

![Screen Shot 2019-06-21 at 16 52 38](https://user-images.githubusercontent.com/3044265/59965206-fa9dc080-94d8-11e9-8a3b-b87d73818b53.png)

**Comment by akevalion** [comment]
There is a small fix for RSTreeLayout, not for the HorizontalTreeLayout
The algorithm to produce that visualization was simple.
- Before it was the recursive method `layout:atPoint:atLayer:`
- on the execution of this method the elements were translated to their positions just one time.
- Now this method can use the method `RSElement>>#translateTo:` two times, This can affect the speed of the layout.

There are these posible solutions:

- Use the mock element and mock edge 
- events and updates in elements at the beginning of the layout, then activate them again

![image](https://user-images.githubusercontent.com/10532890/62251049-949c3700-b3bc-11e9-9bb0-297960f17935.png)
