### ISSUE TITLE
Support Level of Detail simplification for text

### ISSUE THREAD

**Issue by tinchodias** [ObjectProfile/Roassal3#56]
Due to zoom out effect, text labels can be illegible so probably a view render can be optimized by drawing a horizontal line instead. Example of the scenario:

<img width="434" alt="Screen Shot 2019-06-25 at 11 05 32" src="https://user-images.githubusercontent.com/3044265/60110026-6d0cdb80-9739-11e9-900b-ae09868ac7ed.png">

I read this technique is called [Level of Detail](https://en.wikipedia.org/wiki/Level_of_detail) in 3d rendering, that simplifies the polygons and textures that are too far away from the camera.

**Comment by tinchodias** [comment]
The size of the horizontal line should be the height of the text. So, I add to this issue: if the height of the text will be much less than a pixel, then it can just be ignored in rendering. I mean, something like:

* [ textHeight > 3 pixels ] => [ renderText ]
* [ textHeight <= 3 pixels ] => [ renderLine ]
* [ textHeight < 0.5 pixels ] => [ doNothing ]

What do you think?

**Comment by bergel** [comment]
Make sense to me. We could have 8 pixels and 3 pixels as thresholds instead.

**Comment by akevalion** [comment]
In this case should I put and interaction for the canvas to do that or is this supposed to be the default behavior of rendering for RSLabel?

**Comment by akevalion** [comment]
Do we still need this?

**Comment by akevalion** [comment]
Created new class to handle this behaviour RSZoomLevelText
https://user-images.githubusercontent.com/10532890/195396232-9734a609-2087-4cb1-a3f7-497d2cbb0406.mov
