### ISSUE TITLE
Loading Roassal-Pharo9 in Pharo 11 introduces an infinite loop inSpDroplistPresenter

### ISSUE THREAD

**Issue by ClotildeToullec** [ObjectProfile/Roassal3#561]
In baseline: 
```Smalltalk
baselineForPharo11: spec
	self baselineForPharo10: spec
```
and
```Smalltalk
baselineForPharo10: spec
"..."
	spec package: #'Roassal3-Pharo9'.
"..."
```

This package includes a method `SpDropListPresenter>>#displayIcon:`:
```Smalltalk
displayIcon: aBlock
	self iconBlock: aBlock
```

In Pharo 11, `#displayBlock` has been deprecated and is automatically replaced by `#displayIcon:`.
We thus get a recursive call: 
```Smalltalk
displayIcon: aBlock
	self displayIcon: aBlock
```

**Comment by akevalion** [comment]
Fixed

You can find it here https://github.com/ObjectProfile/Roassal3/releases/tag/v1.01b
