### ISSUE TITLE
RSViolinPlot feedback

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/Roassal3#567]
From hernan we have this

## Data Input
Source | Status | Suggested method | Priority | Example
-- | -- | -- | -- | --
Array | OK |   |  
DataFrame | MISSING | #fromDataFrame: | HIGH | \| toothGrowthDose \| toothGrowthDose := AIDatasets loadToothGrowth. (RSViolinPlot fromDataFrame: toothGrowthDose) open.
Array of arrays | MISSING | #fromCollection: | HIGH | \| toothGrowthDose \| toothGrowthDose := (AIDatasets loadToothGrowth) column: 'dose'. (RSViolinPlot fromCollection: toothGrowthDose asArray) open.

## Colors
Feature | Status | Suggested method | Priority | Example
-- | -- | -- | -- | --
Area color | OK | #color: acts as #areaColor: | LOW |
Line colors (the white vertical line represents the line color) | MISSING | #centerLineColor:, #medianLineColor: | NORMAL | ![customized-violin-plot-r](https://github.com/ObjectProfile/Roassal3/assets/10532890/a48409b6-bb51-4ab0-9a1e-2410e1f7cb73)
Border color | MISSING | #borderColor: aColor "Apply the same border color to any violin"#borderColors: aCollectionOfColor "Apply the border colors in aCollectionOfColor to the violin groups" | NORMAL | ![ggplot2-violin-plot-change-group-line-colors-data-visualization-1](https://github.com/ObjectProfile/Roassal3/assets/10532890/c9686c2f-c502-4709-b725-dbe120bc12dd) 
Median color | MISSING | #medianColor:, #medianColor: | NORMAL |  ![ggplot2-violin-plot-add-mean-median-points-data-visualization-2](https://github.com/ObjectProfile/Roassal3/assets/10532890/45dc858f-6b37-4e15-9fda-3b4a0fae05ab)
Mean color | MISSING | #meanColor:, #meanColor | NORMAL |  ![add-mean-violinplot](https://github.com/ObjectProfile/Roassal3/assets/10532890/94381195-15b6-405a-ab9d-3ce0e574be74)
Color fill by group | MISSING | #colorFillByGroup: aCollectionOfColor "Fill the violins with aCollectionOfColor in order (i.e. aCollectionOfColor first is applied to Violin 1, aCollectionOfColor second is applied to Violin 2, etc | HIGH |  ![ggplot2-violin-plot-change-colors-data-visualization-2](https://github.com/ObjectProfile/Roassal3/assets/10532890/ce5b70be-54db-4e68-81f1-4e1907f91ced)

## Grouping + Overlays

Feature | Status | Suggested method | Priority | Example
-- | -- | -- | -- | --
Box plot distribution inside violin | OK |   |  
Scatter plot distribution | MISSING | specialize #createBox ? | NORMAL |  ![scatter_violins-1](https://github.com/ObjectProfile/Roassal3/assets/10532890/0fd92989-2125-4068-9b5c-5c088e1122a3)
Box plot width | MISSING | #boxWidth: | NORMAL |  
Scatter plot width | MISSING | #scatterPlotWidth: | NORMAL |  
Subgroups (Example: groups are days of the week, and subgroups are Males and Females) | MISSING |   | HIGH |  ![unnamed-chunk-1-1](https://github.com/ObjectProfile/Roassal3/assets/10532890/d2259267-a3c7-4a59-bfc0-cc731aaa9b82)
Multiple groups | MISSING | #fromLevels: or #fromSubsets: or #fromGroups: etc. | HIGH |  ![ggplot2-violin-plot-change-colors-data-visualization-2](https://github.com/ObjectProfile/Roassal3/assets/10532890/ce5b70be-54db-4e68-81f1-4e1907f91ced)
Sort violin plots by groups (Violin plots are ordered by default by the order of the levels(groups) of the categorical variable) | MISSING | #orderByGroup: aSymbol ascending: aBoolean or #reorderByGroup: aSymbol | HIGH |  ![reorder-violin-plot](https://github.com/ObjectProfile/Roassal3/assets/10532890/c7bff8c2-4782-46c4-8f95-a3eaa3d1dcbf)

## Miscellany

Feature | Status | Suggested method | Priority | Example
-- | -- | -- | -- | --
Set Bandwith | OK |   |  
Rotate | MISSING | #rotate: or #beHorizontal, #beVertical | NTH |  ![ing](https://github.com/ObjectProfile/Roassal3/assets/10532890/24207d4f-4cea-4565-a699-1af625fcdc77)
Trimming | MISSING | #enableTrimming, #disableTrimming | NTH |  ![Truncated vs Extended](https://github.com/ObjectProfile/Roassal3/assets/10532890/e13de417-8edb-4545-ac3a-6c493bedd012)
Set mean shape + size (A point present at the center of the plot indicates the mean point) | MISSING | #useMeanPointRange, #useMeanPointRangeWithSize: #useMeanPoint, #useMeanPointWithSize: | NORMAL |  
Set median shape + size | MISSING | #useMedianPointRange, #useMedianPointRangeWithSize: #useMedianPoint, #useMedianPointWithSize: | NORMAL

**Comment by akevalion** [comment]
# Missing
- DataFrame: create bridge package between Roassal and DataFrame
- Mean color:
- Mean shape configuration to set the correct shape?
  - Set mean shape + size
  - Set median shape + size
- Scatter plot distribution
- Sort violin plots by groups
- Rotate
- Trimming
# Review
- Multiple groups

**Comment by akevalion** [comment]
For rotate code

```st
barPlot := RSBarPlot new.
"RSHorizontalBarPlot new"
...
barPlot beHorizontal.
"another option"
invertStrategy := RSInvertCoordinates new.
barPlot add: invertStrategy.
barPlot coordinates: invertStrategy.
barPlot orientation: invertStrategy.

barPlot open
```

RSAbstractPlot >> #renderInWithCoordinates: aCanvas
    self renderIn: aCanvas.
    coordinates adjustPlots: shapes.

**Comment by kevca87** [comment]
### Array of arrays

```smalltalk
| boxPlot1 |
boxPlot1 := self data: {{6. 8. 7. 5. 7. 11. 9. }. {2. 2. 2. 3. 3. 12. 4. 2. 4. 2. 2. 2. 6. 2. 2. 8. 2. 5. 9. 2. 2. 2. 2. 2.}. }.
boxPlot1 open
```
<img src="https://github.com/ObjectProfile/Roassal3/assets/74360938/066fa9ed-dc88-4d3c-b06e-4afe86210fbf" width=350>

**Comment by kevca87** [comment]
### Border color ✅ 
#### `borderColor:`
```smalltalk
| violinPlot1 data1 |
data1 := {{6. 8. 7. 5. 7. 11. 9. }. { 12. 12. 13. 15. 18. 20. 21. 24. }}.
violinPlot1 := self data: data1.
violinPlot1 borderColor: Color red.
violinPlot1 open
```
![image](https://github.com/ObjectProfile/Roassal3/assets/74360938/7e891ff5-23b9-4966-83e8-0ebe50ad78ea)

#### `borderColors:`
```smalltalk
| violinPlot1 data1 |
data1 := {{6. 8. 7. 5. 7. 11. 9. }. { 12. 12. 13. 15. 18. 20. 21. 24. }}.
violinPlot1 := self data: data1.
violinPlot1 borderColors: {Color red. Color purple.}.
violinPlot1 open
```
![image](https://github.com/ObjectProfile/Roassal3/assets/74360938/27dd38a2-ce03-4337-b7fa-decd840ccb6a)

#### Border accessing style (of each violin)
```smalltalk
| violinPlot2 data2 |
data2 := {{ 12. 12. 13. 15. 18. 20. 21. 24. }.{15. 15. 18. 12. 13. 10. 11. 14.}. {14. 14. 16. 12. 13. 10. 11. 14.}.}.
violinPlot2 := self data: data2.
violinPlot2 borders first color: Color red; dashArray: { 4. }. "way 1"
violinPlot2 violinShapes second borderColor: Color orange. "way 2"
violinPlot2 violinShapes third border color: Color green. "way 3"
violinPlot2 open
```
![image](https://github.com/ObjectProfile/Roassal3/assets/74360938/ffe516cc-bbdb-460d-b94e-c9228bde01a6)

**Comment by akevalion** [comment]
We can close this issue as completed
