### ISSUE TITLE
Merge RSOptimizedForceBasedLayout with superclass

### ISSUE THREAD

**Issue by tinchodias** [ObjectProfile/Roassal3#57]
Looks like the superclass is slow because it translates elements several times on each step... so the optimized approach should make sense always. Or is there a case where it's better to use the unoptimized, @bergel ?

**Comment by bergel** [comment]
Not that I know. Please, do the merging...

**Comment by akevalion** [comment]
I have cleaning the class of RSForceBasedLayout. Pair programming with Martín

**Comment by bergel** [comment]
Well done!
