### ISSUE TITLE
Border color

### ISSUE THREAD

**Issue by DurieuxPol** [ObjectProfile/Roassal3#572]
`RSLine` base color, and this may also be the case for some other shapes, is the color of their border (`RSBorder`) instead of their own, which is a bit odd. I don't know if it is intentional or not, and if it is the best way.
For example (with the example02 of Boxplot): 
![image](https://github.com/ObjectProfile/Roassal3/assets/124769707/47cf4bab-b353-42d2-be2f-1750a0459815)
I only changed the color in the `initialize` of `RSBorder`.

**Comment by akevalion** [comment]
In these case to change the line color there are 3 strategies

- use instance variables in box plot
```st
boxPlot lineColor: Color gren.
```
- use a RSChartStyler and object to get this properties as colors
```st
boxPlot styler lineColor: Color green. 
```
- use a master object(this is used in box plot right now), one object to mod
```st
boxPlot lineShape color: Color green
```

Let me know if this issue is still valid

**Comment by akevalion** [comment]
To draw shapes in roassal, we need an stroke paint(usually a border with solid color) and a fill paint(usually another color) over a path in cairo.

Then in roassal there are some Lines that can use the stroke and the fill paint. But stroke is complex object, it may have width size, dasyArray, cap and join styles, thats why RSBorder solve this problem.

RSLine has a both the fill paint in instance variable `paint` and the stroke paint in `border`.
But the `cairo path` the line builds only uses the stroke paint.
