### ISSUE TITLE
Enable Frames per second (FPS) in view

### ISSUE THREAD

**Issue by tinchodias** [ObjectProfile/Roassal3#58]
Story: I have a view with an animated (optimized) force layout that after few seconds makes the cooler start due to high CPU usage. The animation is neat, quite fluid, so I wonder if limiting the steps per second is a good option. Then, I commented to Milton the idea of showing the FPS and he said it was a good idea to add it as an interaction.

**Comment by akevalion** [comment]
There is a new interaction for this issue `RSMonitorView`

```Smalltalk

	| v classes layout |
	v := RSView new.
	classes := RSShapeBuilder ellipse
		draggable;
		color: Color purple trans;
		size: 10;
		if: [ :cls | cls = Collection ] then: [ :s | s color: Color red ];
		elementsOn: Collection withAllSubclasses.

	RSEdgeBuilder line
		view: v;
		elements: classes;
		color: (Color purple alpha: 0.2);
		connectFrom: #superclass to: #yourself.
	v addAll: classes.
	layout := RSForceBasedLayout new 
		nodes: classes;
		edges: v edges;
		start: classes;
		yourself.
	v animation repeat onStepDo: [ :t | 
		layout step ].
	v @ RSMonitorView.
	v open
```
![image](https://user-images.githubusercontent.com/10532890/60624422-40993500-9db3-11e9-8d6c-184e5af9f2e7.png)

**Comment by tinchodias** [comment]
Great! I close this, then.
However, text color of current ui theme would be better IMHO :)
