### ISSUE TITLE
RSStyler

### ISSUE THREAD

**Issue by DurieuxPol** [ObjectProfile/Roassal3#580]
I wanted to change label color for horizontal top ticks only for DoubleBar plot, but it changed for the horizontal ticks and vertical ticks also.
The issue seems to be that all ticks have the same styler object.

Here is an example:
```Smalltalk
p := RSLinePlot new x: #(1 2 3) y: #(2 3 4).
p horizontalTick styler textColor: Color red.
p open
```

![image](https://github.com/ObjectProfile/Roassal3/assets/124769707/35c8c398-b445-4bb8-9acb-84a9887932a2)

**Comment by akevalion** [comment]
You can use
```st
p := RSLinePlot new x: #(1 2 3) y: #(2 3 4).
p horizontalTick styler: (RSChartStyler new textColor: Color red).

p open
```
