### ISSUE TITLE
RoassalPresenter: remember last view?

### ISSUE THREAD

**Issue by tinchodias** [ObjectProfile/Roassal3#66]
The HiMNavigatorPresenter uses the RoassalPresenter this way:
~~~
	viewPresenter := (self instantiate: RoassalPresenter)
		script: [ :newView |
			lastView := newView.
			self fillLastView ];
		yourself.
~~~
i.e. it stores in an instvar the view created by the RoassalPresenter because it interacts with when buttons are pressed among others. 

More concretely, I have these two uses:
`lastView signalUpdate` and  `lastView elementFromModel: ...`, and may be transformed into something like `viewPresenter view signalUpdate` and  `viewPresenter view elementFromModel: ...`.

I'm not completely sure of this request.

**Comment by akevalion** [comment]
I have created a new methods canvas en SpRoassalPresenter this allow to the use access directly to the current RSCanvas

**Comment by akevalion** [comment]
Can we close this issue?
