### ISSUE TITLE
Create a window to visualize the color palettes

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/Roassal3#67]
We need a basic window, it could be in spec accessible from the menu world that allows us to see the colors

**Comment by akevalion** [comment]
There is a new window for roassal3 color palettes. This window allows to the user see the palette colors and interact with the palettes copying the colors or the paletes to the clipboard

![image](https://user-images.githubusercontent.com/10532890/61833840-99ed0500-ae43-11e9-91b0-a052f52fba46.png)

**Comment by bergel** [comment]
Excellent! Works very well!
