### ISSUE TITLE
Memory issue with Spec

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/Roassal3#68]
There is a memory issue about presenters with roassal
Here there is a smallscript
```Smalltalk
logBlock := [TSAthensMorph allInstances size logCr. Transcript flush].

logBlock value. "Initial log"
 
w := RSColorPaletteChooser new openWithSpec.
[    500 milliSeconds wait.
    w close.
    w := nil.
    3 timesRepeat: [Smalltalk garbageCollect. 50 milliSeconds wait ].

    logBlock value. "Ending log"

] fork.
```
Explanation, each time you open a presenter the window remains, because there is a references between RoassalPresenter and the SpWindowPresenter.

You can solve this issue with the message `close` in SpWindowPresenter, as You can see script.

This instruction closes the window and the roassal presenter properly.

If you try to close the window with the mouse and the close button, the window and the roassal presenter will remain in memory, that is the issue.

**Comment by akevalion** [comment]
Update

I have loaded Pharo8x64bits. This issue is reproducible on other examples of Spec2.

- Execute `SpInputTextDropList new openWithSpec`
- Close the new window with window's button
- The run the next code
```Smalltalk
SpInputTextDropList allInstances.
Smalltalk garbageCollect.
Object new.
```

Each time you open an instance of SpInputTextDropList you still have the object active in the image memory.

The window does not close properly the objects

**Comment by akevalion** [comment]
This issue can be resolved using
`SpNullApplication reset`

**Comment by bergel** [comment]
This is a problem of Spec, not really of Roassal
