### ISSUE TITLE
We need an interaction for the treelayout and rectangle pack layout

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/Roassal3#72]
Martin has created a nice interaction with RSTreeLayout an RSRectanglePackLayout. 
We need that in roassal as a basic interaction

**Comment by akevalion** [comment]
There is a new version of roassal3 with RSRectanglePackLayout with a simple example 
![image](https://user-images.githubusercontent.com/10532890/62491735-bde10c80-b79a-11e9-8dba-73db144c2f9c.png)

**Comment by akevalion** [comment]
I think that we can close this issue RSHierarchyPacker is an interaction that moves the shapes by hierarchy and put events to the canvas to change the position of each node
```Smalltalk
| builder classes |
builder := RSUMLClassBuilder new.
classes := { 'Roassal3-Layouts'. 'Roassal3' }
	flatCollect: [:pkgname | (RPackage organizer
		packageNamed: pkgname) definedClasses ].
builder classes: classes.
builder renderer: RSTorchUMLClassRenderer new.
builder build.
builder canvas @ RSHierarchyPacker.
^ builder canvas.
```

Think that we can close this issue

**Comment by bergel** [comment]
Is there a reason why `RSHierarchyPacker` only works with `RSRectanglePackLayout` ?

**Comment by bergel** [comment]
Anyway, seems to work well for `RSRectanglePackLayout`. Well done!
