### ISSUE TITLE
Add dependency to spec2 in pharo7

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/Roassal3#74]
Roassal3 has a dependency to spec2, it does not work when it loads on pharo7

**Comment by akevalion** [comment]
There is a new version of the baseline of roassal3 for pharo7

**Comment by tinchodias** [comment]
An option is to set the package(s) that depend in Spec2 loadable only when it's pharo >= 8

**Comment by bergel** [comment]
not necessary
