### ISSUE TITLE
Improve calculation of label width

### ISSUE THREAD

**Issue by tinchodias** [ObjectProfile/Roassal3#79]
Debugging apparently indicates that there is some estimation error in the widthOfText algorithm in `AbstractFont`.

See at the end of the box:

![Screen Shot 2019-08-09 at 16 41 15](https://user-images.githubusercontent.com/3044265/62808012-edf31d00-bac4-11e9-8a6f-25aebec26a75.png)

```
aString := String new: 50 withAll: $o.

v := RSView new.

aLabel := TSLabel new
	text: aString;
	yourself.
v addShape: aLabel.
v addShape: (TSBox new 
	color: Color gray trans;
	extent: aLabel extent;
	yourself).
v
```

It can make the labels look a bit miss-aligned, but it's quite subtle anyway:

![Screen Shot 2019-08-09 at 16 57 23](https://user-images.githubusercontent.com/3044265/62808684-cef58a80-bac6-11e9-8697-693522eeb1a1.png)

**Comment by bergel** [comment]
Updated script:
```Smalltalk
aString := String new: 50 withAll: $o.

v := RSView new.

aLabel := TSLabel new
	text: aString;
	yourself.
v addShape: aLabel.
v addShape: (TSBox new 
	color: Color gray trans;
	extent: aLabel extent;
	yourself).
v
```

**Comment by akevalion** [comment]
Update 
```Smalltalk 
aString := String new: 50 withAll: $o.

v := RSCanvas new.

aLabel := RSLabel new
	text: aString;
	yourself.
v addShape: aLabel.
v addShape: (RSBox new 
	color: Color gray translucent;
	extent: aLabel extent;
	yourself).
v @ RSCanvasController
```

In some few cases the text width fail.

![image](https://user-images.githubusercontent.com/10532890/84473609-61bb0480-ac57-11ea-8bf8-033eac1060be.png)

I have changed a the way of compute the text width and height for RSLabel

![image](https://user-images.githubusercontent.com/10532890/84473721-8f07b280-ac57-11ea-82e5-33e66f2266ea.png)

![image](https://user-images.githubusercontent.com/10532890/84473765-9fb82880-ac57-11ea-9288-d12dd5cd875f.png)

![image](https://user-images.githubusercontent.com/10532890/84473809-b0689e80-ac57-11ea-9111-fed69245d440.png)

![image](https://user-images.githubusercontent.com/10532890/84474311-a09d8a00-ac58-11ea-95ec-056c35501d42.png)

![image](https://user-images.githubusercontent.com/10532890/84474616-21f51c80-ac59-11ea-8f39-aec3378e2557.png)

![image](https://user-images.githubusercontent.com/10532890/84476111-aea0da00-ac5b-11ea-8748-cce8237d0a8c.png)

**Comment by bergel** [comment]
The calculation is not perfect, but we have improved it.

**Comment by akevalion** [comment]
The calculation sometimes fails with `CairoFontMetricsProvider `

**Comment by akevalion** [comment]
There is a new RSCairoMetricsProvider, then it is more accurate the width of each label.

**Comment by bergel** [comment]
Solved apparently:
```Smalltalk
aString := String new: 50 withAll: $o.

v := RSCanvas new.

aLabel := RSLabel new
	metricsProvider: (RSCairoFitMetricsProvider new);
	text: aString;
	yourself.
v addShape: aLabel.
v addShape: (RSBox new 
	color: Color gray translucent;
	extent: aLabel extent;
	yourself).
v @ RSCanvasController
```
produces:
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/393742/93940614-18d21c00-fd2d-11ea-8a24-bf3bf09a6792.png">


And without a metric provider:
```Smalltalk
aString := String new: 50 withAll: $o.

v := RSCanvas new.

aLabel := RSLabel new
	text: aString;
	yourself.
v addShape: aLabel.
v addShape: (RSBox new 
	color: Color gray translucent;
	extent: aLabel extent;
	yourself).
v @ RSCanvasController
```
it produces:
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/393742/93940632-25ef0b00-fd2d-11ea-809b-9fbbed980c56.png">
