### ISSUE TITLE
Review a short way to put events in a shape

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/Roassal3#8]
Current state
```Smalltalk
view := RSView new.
....
box when: TSTranslationShapeEvent do: [:evt | ... ].
view when: TSResizeCanvasEvent do: [ :evt | pie view zoomToFit ].
```
I think that we have long names for these events, may be we can use

```Smalltalk
box when: #positionChanged do: [:evt | ... ].
view when: #extentChanged do: [ :evt | pie view zoomToFit ].
```

**Comment by bergel** [comment]
Could be. But `box when: TSTranslationShapeEvent do: [:evt | ... ].` makes it clear which kind of event one can subscribe to: you only look at the class hierarchy of `TSEvent` for example.
Where `#extentChanged` and `#positionChanged` would be defined?

**Comment by akevalion** [comment]
For `TSCanvas` `TSShape` and `TSCamera`
1. `TSCanvas` uses TSExtentChangedEvent instead of TSResizeCanvasEvent
2. Shape could use TSExtentChangedEvent and TSPositionChangedEvent
3. TSCamera could use TSPositionChangedEvent and TSScaleChangedEvent

**Comment by bergel** [comment]
I prefer to have the class instead of an arbitrary symbol
