### ISSUE TITLE
Push extensions to Pharo 8.0 :)

### ISSUE THREAD

**Issue by Ducasse** [ObjectProfile/Roassal3#88]
- Athens
- Announcer extensions

**Comment by Ducasse** [comment]
Rectangle >> rsCenter -> Rectangle >> floatCenter

**Comment by akevalion** [comment]
I have created a new pull request.
https://github.com/pharo-project/pharo/pull/4405

- Rectangle >> floatCenter and Rectangle class >> floatCenter:extent:
- New test for Rectangle.
- Announcer and SubscriptionRegistry, about accessing subscribers by a class.
- New Mock classes for test.
- New test for Announcer Test.
- Added new ffi class for Athens
- Added new example for AthensCairoSurfaceExample class >> exampleDrawTextPath that generates the next picture in the pharo image.

![image](https://user-images.githubusercontent.com/10532890/63586188-125cf800-c5a1-11e9-928b-161f4393dea4.png)

**Comment by Ducasse** [comment]
Milton 
Thanks now for the PR it is better to make them focusing on one point: 
- rectangle and tests for rectangle
- announcer 
- ...
this way it is simpler to review.

**Comment by akevalion** [comment]
I will keep it in that way

**Comment by akevalion** [comment]
I think that we can close this issue

**Comment by akevalion** [comment]
x2
