### ISSUE TITLE
RTGrapher examples doesn't work

### ISSUE THREAD

**Issue by mahugnon** [ObjectProfile/Roassal3#93]
b := RTGrapher new.
ds := RTDataSet new. 
ds dotShape color: Color red. 
ds points: #(5 1 20 8).
b add: ds.
b build.

**Comment by bergel** [comment]
Your code is for Roassal2. It should be:
```Smalltalk
b := RTGrapher new.
ds := RTData new.
ds dotShape color: Color red.
ds points: #(5 1 20 8).
b add: ds.
b build.
```
and it produces:
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/393742/71036677-e8ee4c00-20fc-11ea-8ff9-494146a323ec.png">
as expected
