### ISSUE TITLE
is RSAbstractShapeBuilder really necessary?

### ISSUE THREAD

**Issue by bergel** [ObjectProfile/Roassal3#99]
Currently, it has only subclasses, `RSSimplePopup`. This is weird...

**Comment by akevalion** [comment]
RSAbstractShapeBuilder defines the methods `onShape: anObject`
RSSimplePopup defines this method
BlockClosure also defines this method

The idea is to have classes for UML that defines this method, similar to `RTInteraction >> onShape:`

**Comment by akevalion** [comment]
After editing UML for roassal this class is not longer need it

**Comment by bergel** [comment]
This class was replaced by `RSShapeFactory`
